set(AFB_REMPORT "1234")
set(AFB_TOKEN "1234")
set(API_NAME "shell")
set(BINDINGS_LINK_FLAG "-Xlinker -rpath=/usr/local/lib64")
set(BINDIR "bin")
set(BUILD_ENV_SYSROOT "bin")
set(BUILD_TEST_WGT "bin")
set(BUILD_TYPE "DEBUG")
set(Blue "[34m")
set(BoldBlue "[1;34m")
set(BoldCyan "[1;36m")
set(BoldGreen "[1;32m")
set(BoldMagenta "[1;35m")
set(BoldRed "[1;31m")
set(BoldWhite "[1;37m")
set(BoldYellow "[1;33m")
set(CLOSING_MESSAGE "Debug: afb-binder --name=afb-oidc --config=../conf.d/project/etc/oidc-config.json --rootdir=../conf.d/project/htdocs --verbose # http://localhost:1234/devtools/index.html")
set(CMAKE_ADDR2LINE "/usr/bin/addr2line")
set(CMAKE_AR "/usr/bin/ar")
set(CMAKE_AR "/usr/bin/ar")
set(CMAKE_AUTOGEN_ORIGIN_DEPENDS "ON")
set(CMAKE_AUTOMOC_COMPILER_PREDEFINES "ON")
set(CMAKE_AUTOMOC_MACRO_NAMES "Q_OBJECTQ_GADGETQ_NAMESPACEQ_NAMESPACE_EXPORT")
set(CMAKE_AUTOMOC_PATH_PREFIX "Q_OBJECTQ_GADGETQ_NAMESPACEQ_NAMESPACE_EXPORT")
set(CMAKE_BASE_NAME "g++")
set(CMAKE_BINARY_DIR "/home/fulup/Workspace/AFB-binder/sec-gate-oidc/build")
set(CMAKE_BUILD_TOOL "/usr/bin/gmake")
set(CMAKE_BUILD_TYPE "DEBUG")
set(CMAKE_BUILD_WITH_INSTALL_RPATH "true")
set(CMAKE_C11_COMPILE_FEATURES "c_std_11c_static_assert")
set(CMAKE_C11_EXTENSION_COMPILE_OPTION "-std=gnu11")
set(CMAKE_C11_STANDARD_COMPILE_OPTION "-std=c11")
set(CMAKE_C11_STANDARD__HAS_FULL_SUPPORT "ON")
set(CMAKE_C90_COMPILE_FEATURES "c_std_90c_function_prototypes")
set(CMAKE_C90_EXTENSION_COMPILE_OPTION "-std=gnu90")
set(CMAKE_C90_STANDARD_COMPILE_OPTION "-std=c90")
set(CMAKE_C90_STANDARD__HAS_FULL_SUPPORT "ON")
set(CMAKE_C99_COMPILE_FEATURES "c_std_99c_restrictc_variadic_macros")
set(CMAKE_C99_EXTENSION_COMPILE_OPTION "-std=gnu99")
set(CMAKE_C99_STANDARD_COMPILE_OPTION "-std=c99")
set(CMAKE_C99_STANDARD__HAS_FULL_SUPPORT "ON")
set(CMAKE_CFG_INTDIR ".")
set(CMAKE_COLOR_MAKEFILE "ON")
set(CMAKE_COMMAND "/usr/bin/cmake")
set(CMAKE_COMPILER_IS_GNUCC "1")
set(CMAKE_COMPILER_IS_GNUCXX "1")
set(CMAKE_CPACK_COMMAND "/usr/bin/cpack")
set(CMAKE_CROSSCOMPILING "/usr/bin/cpack")
set(CMAKE_CTEST_COMMAND "/usr/bin/ctest")
set(CMAKE_CURRENT_BINARY_DIR "/home/fulup/Workspace/AFB-binder/sec-gate-oidc/build")
set(CMAKE_CURRENT_LIST_DIR "/usr/share/cmake/Modules/CMakeAfbTemplates/cmake/cmake.d")
set(CMAKE_CURRENT_LIST_FILE "/usr/share/cmake/Modules/CMakeAfbTemplates/cmake/cmake.d/04-extra_targets.cmake")
set(CMAKE_CURRENT_SOURCE_DIR "/home/fulup/Workspace/AFB-binder/sec-gate-oidc")
set(CMAKE_CXX11_COMPILE_FEATURES "cxx_std_11cxx_alias_templatescxx_alignascxx_alignofcxx_attributescxx_auto_typecxx_constexprcxx_decltypecxx_decltype_incomplete_return_typescxx_default_function_template_argscxx_defaulted_functionscxx_defaulted_move_initializerscxx_delegating_constructorscxx_deleted_functionscxx_enum_forward_declarationscxx_explicit_conversionscxx_extended_friend_declarationscxx_extern_templatescxx_finalcxx_func_identifiercxx_generalized_initializerscxx_inheriting_constructorscxx_inline_namespacescxx_lambdascxx_local_type_template_argscxx_long_long_typecxx_noexceptcxx_nonstatic_member_initcxx_nullptrcxx_overridecxx_range_forcxx_raw_string_literalscxx_reference_qualified_functionscxx_right_angle_bracketscxx_rvalue_referencescxx_sizeof_membercxx_static_assertcxx_strong_enumscxx_thread_localcxx_trailing_return_typescxx_unicode_literalscxx_uniform_initializationcxx_unrestricted_unionscxx_user_literalscxx_variadic_macroscxx_variadic_templates")
set(CMAKE_CXX11_EXTENSION_COMPILE_OPTION "-std=gnu++11")
set(CMAKE_CXX11_STANDARD_COMPILE_OPTION "-std=c++11")
set(CMAKE_CXX11_STANDARD__HAS_FULL_SUPPORT "ON")
set(CMAKE_CXX14_COMPILE_FEATURES "cxx_std_14cxx_aggregate_default_initializerscxx_attribute_deprecatedcxx_binary_literalscxx_contextual_conversionscxx_decltype_autocxx_digit_separatorscxx_generic_lambdascxx_lambda_init_capturescxx_relaxed_constexprcxx_return_type_deductioncxx_variable_templates")
set(CMAKE_CXX14_EXTENSION_COMPILE_OPTION "-std=gnu++14")
set(CMAKE_CXX14_STANDARD_COMPILE_OPTION "-std=c++14")
set(CMAKE_CXX14_STANDARD__HAS_FULL_SUPPORT "ON")
set(CMAKE_CXX17_COMPILE_FEATURES "cxx_std_17")
set(CMAKE_CXX17_EXTENSION_COMPILE_OPTION "-std=gnu++17")
set(CMAKE_CXX17_STANDARD_COMPILE_OPTION "-std=c++17")
set(CMAKE_CXX20_COMPILE_FEATURES "cxx_std_20")
set(CMAKE_CXX20_EXTENSION_COMPILE_OPTION "-std=gnu++2a")
set(CMAKE_CXX20_STANDARD_COMPILE_OPTION "-std=c++2a")
set(CMAKE_CXX98_COMPILE_FEATURES "cxx_std_98cxx_template_template_parameters")
set(CMAKE_CXX98_EXTENSION_COMPILE_OPTION "-std=gnu++98")
set(CMAKE_CXX98_STANDARD_COMPILE_OPTION "-std=c++98")
set(CMAKE_CXX98_STANDARD__HAS_FULL_SUPPORT "ON")
set(CMAKE_CXX_ABI_COMPILED "TRUE")
set(CMAKE_CXX_ARCHIVE_APPEND "<CMAKE_AR> q <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_CXX_ARCHIVE_APPEND_IPO "\"/usr/bin/gcc-ar\" r <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_CXX_ARCHIVE_CREATE "<CMAKE_AR> qc <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_CXX_ARCHIVE_CREATE_IPO "\"/usr/bin/gcc-ar\" cr <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_CXX_ARCHIVE_FINISH "<CMAKE_RANLIB> <TARGET>")
set(CMAKE_CXX_ARCHIVE_FINISH_IPO "\"/usr/bin/gcc-ranlib\" <TARGET>")
set(CMAKE_CXX_CL_SHOWINCLUDES_PREFIX "\"/usr/bin/gcc-ranlib\" <TARGET>")
set(CMAKE_CXX_COMPILER "/usr/bin/c++")
set(CMAKE_CXX_COMPILER "/usr/bin/c++")
set(CMAKE_CXX_COMPILER_ABI "ELF")
set(CMAKE_CXX_COMPILER_AR "/usr/bin/gcc-ar")
set(CMAKE_CXX_COMPILER_AR "/usr/bin/gcc-ar")
set(CMAKE_CXX_COMPILER_ARCHITECTURE_ID "/usr/bin/gcc-ar")
set(CMAKE_CXX_COMPILER_ARG1 "/usr/bin/gcc-ar")
set(CMAKE_CXX_COMPILER_ENV_VAR "CXX")
set(CMAKE_CXX_COMPILER_FRONTEND_VARIANT "CXX")
set(CMAKE_CXX_COMPILER_ID "GNU")
set(CMAKE_CXX_COMPILER_ID_PLATFORM_CONTENT "#define STRINGIFY_HELPER(X) #X\n#define STRINGIFY(X) STRINGIFY_HELPER(X)\n\n/* Identify known platforms by name.  */\n#if defined(__linux) || defined(__linux__) || defined(linux)\n# define PLATFORM_ID \"Linux\"\n\n#elif defined(__CYGWIN__)\n# define PLATFORM_ID \"Cygwin\"\n\n#elif defined(__MINGW32__)\n# define PLATFORM_ID \"MinGW\"\n\n#elif defined(__APPLE__)\n# define PLATFORM_ID \"Darwin\"\n\n#elif defined(_WIN32) || defined(__WIN32__) || defined(WIN32)\n# define PLATFORM_ID \"Windows\"\n\n#elif defined(__FreeBSD__) || defined(__FreeBSD)\n# define PLATFORM_ID \"FreeBSD\"\n\n#elif defined(__NetBSD__) || defined(__NetBSD)\n# define PLATFORM_ID \"NetBSD\"\n\n#elif defined(__OpenBSD__) || defined(__OPENBSD)\n# define PLATFORM_ID \"OpenBSD\"\n\n#elif defined(__sun) || defined(sun)\n# define PLATFORM_ID \"SunOS\"\n\n#elif defined(_AIX) || defined(__AIX) || defined(__AIX__) || defined(__aix) || defined(__aix__)\n# define PLATFORM_ID \"AIX\"\n\n#elif defined(__hpux) || defined(__hpux__)\n# define PLATFORM_ID \"HP-UX\"\n\n#elif defined(__HAIKU__)\n# define PLATFORM_ID \"Haiku\"\n\n#elif defined(__BeOS) || defined(__BEOS__) || defined(_BEOS)\n# define PLATFORM_ID \"BeOS\"\n\n#elif defined(__QNX__) || defined(__QNXNTO__)\n# define PLATFORM_ID \"QNX\"\n\n#elif defined(__tru64) || defined(_tru64) || defined(__TRU64__)\n# define PLATFORM_ID \"Tru64\"\n\n#elif defined(__riscos) || defined(__riscos__)\n# define PLATFORM_ID \"RISCos\"\n\n#elif defined(__sinix) || defined(__sinix__) || defined(__SINIX__)\n# define PLATFORM_ID \"SINIX\"\n\n#elif defined(__UNIX_SV__)\n# define PLATFORM_ID \"UNIX_SV\"\n\n#elif defined(__bsdos__)\n# define PLATFORM_ID \"BSDOS\"\n\n#elif defined(_MPRAS) || defined(MPRAS)\n# define PLATFORM_ID \"MP-RAS\"\n\n#elif defined(__osf) || defined(__osf__)\n# define PLATFORM_ID \"OSF1\"\n\n#elif defined(_SCO_SV) || defined(SCO_SV) || defined(sco_sv)\n# define PLATFORM_ID \"SCO_SV\"\n\n#elif defined(__ultrix) || defined(__ultrix__) || defined(_ULTRIX)\n# define PLATFORM_ID \"ULTRIX\"\n\n#elif defined(__XENIX__) || defined(_XENIX) || defined(XENIX)\n# define PLATFORM_ID \"Xenix\"\n\n#elif defined(__WATCOMC__)\n# if defined(__LINUX__)\n#  define PLATFORM_ID \"Linux\"\n\n# elif defined(__DOS__)\n#  define PLATFORM_ID \"DOS\"\n\n# elif defined(__OS2__)\n#  define PLATFORM_ID \"OS2\"\n\n# elif defined(__WINDOWS__)\n#  define PLATFORM_ID \"Windows3x\"\n\n# elif defined(__VXWORKS__)\n#  define PLATFORM_ID \"VxWorks\"\n\n# else /* unknown platform */\n#  define PLATFORM_ID\n# endif\n\n#elif defined(__INTEGRITY)\n# if defined(INT_178B)\n#  define PLATFORM_ID \"Integrity178\"\n\n# else /* regular Integrity */\n#  define PLATFORM_ID \"Integrity\"\n# endif\n\n#else /* unknown platform */\n# define PLATFORM_ID\n\n#endif\n\n/* For windows compilers MSVC and Intel we can determine\n   the architecture of the compiler being used.  This is because\n   the compilers do not have flags that can change the architecture,\n   but rather depend on which compiler is being used\n*/\n#if defined(_WIN32) && defined(_MSC_VER)\n# if defined(_M_IA64)\n#  define ARCHITECTURE_ID \"IA64\"\n\n# elif defined(_M_X64) || defined(_M_AMD64)\n#  define ARCHITECTURE_ID \"x64\"\n\n# elif defined(_M_IX86)\n#  define ARCHITECTURE_ID \"X86\"\n\n# elif defined(_M_ARM64)\n#  define ARCHITECTURE_ID \"ARM64\"\n\n# elif defined(_M_ARM)\n#  if _M_ARM == 4\n#   define ARCHITECTURE_ID \"ARMV4I\"\n#  elif _M_ARM == 5\n#   define ARCHITECTURE_ID \"ARMV5I\"\n#  else\n#   define ARCHITECTURE_ID \"ARMV\" STRINGIFY(_M_ARM)\n#  endif\n\n# elif defined(_M_MIPS)\n#  define ARCHITECTURE_ID \"MIPS\"\n\n# elif defined(_M_SH)\n#  define ARCHITECTURE_ID \"SHx\"\n\n# else /* unknown architecture */\n#  define ARCHITECTURE_ID \"\"\n# endif\n\n#elif defined(__WATCOMC__)\n# if defined(_M_I86)\n#  define ARCHITECTURE_ID \"I86\"\n\n# elif defined(_M_IX86)\n#  define ARCHITECTURE_ID \"X86\"\n\n# else /* unknown architecture */\n#  define ARCHITECTURE_ID \"\"\n# endif\n\n#elif defined(__IAR_SYSTEMS_ICC__) || defined(__IAR_SYSTEMS_ICC)\n# if defined(__ICCARM__)\n#  define ARCHITECTURE_ID \"ARM\"\n\n# elif defined(__ICCRX__)\n#  define ARCHITECTURE_ID \"RX\"\n\n# elif defined(__ICCRH850__)\n#  define ARCHITECTURE_ID \"RH850\"\n\n# elif defined(__ICCRL78__)\n#  define ARCHITECTURE_ID \"RL78\"\n\n# elif defined(__ICCRISCV__)\n#  define ARCHITECTURE_ID \"RISCV\"\n\n# elif defined(__ICCAVR__)\n#  define ARCHITECTURE_ID \"AVR\"\n\n# elif defined(__ICC430__)\n#  define ARCHITECTURE_ID \"MSP430\"\n\n# elif defined(__ICCV850__)\n#  define ARCHITECTURE_ID \"V850\"\n\n# elif defined(__ICC8051__)\n#  define ARCHITECTURE_ID \"8051\"\n\n# else /* unknown architecture */\n#  define ARCHITECTURE_ID \"\"\n# endif\n\n#elif defined(__ghs__)\n# if defined(__PPC64__)\n#  define ARCHITECTURE_ID \"PPC64\"\n\n# elif defined(__ppc__)\n#  define ARCHITECTURE_ID \"PPC\"\n\n# elif defined(__ARM__)\n#  define ARCHITECTURE_ID \"ARM\"\n\n# elif defined(__x86_64__)\n#  define ARCHITECTURE_ID \"x64\"\n\n# elif defined(__i386__)\n#  define ARCHITECTURE_ID \"X86\"\n\n# else /* unknown architecture */\n#  define ARCHITECTURE_ID \"\"\n# endif\n\n#elif defined(__TI_COMPILER_VERSION__)\n# if defined(__TI_ARM__)\n#  define ARCHITECTURE_ID \"ARM\"\n\n# elif defined(__MSP430__)\n#  define ARCHITECTURE_ID \"MSP430\"\n\n# elif defined(__TMS320C28XX__)\n#  define ARCHITECTURE_ID \"TMS320C28x\"\n\n# elif defined(__TMS320C6X__) || defined(_TMS320C6X)\n#  define ARCHITECTURE_ID \"TMS320C6x\"\n\n# else /* unknown architecture */\n#  define ARCHITECTURE_ID \"\"\n# endif\n\n#else\n#  define ARCHITECTURE_ID\n#endif\n\n/* Convert integer to decimal digit literals.  */\n#define DEC(n)                   \\\n  ('0' + (((n) / 10000000)%10)), \\\n  ('0' + (((n) / 1000000)%10)),  \\\n  ('0' + (((n) / 100000)%10)),   \\\n  ('0' + (((n) / 10000)%10)),    \\\n  ('0' + (((n) / 1000)%10)),     \\\n  ('0' + (((n) / 100)%10)),      \\\n  ('0' + (((n) / 10)%10)),       \\\n  ('0' +  ((n) % 10))\n\n/* Convert integer to hex digit literals.  */\n#define HEX(n)             \\\n  ('0' + ((n)>>28 & 0xF)), \\\n  ('0' + ((n)>>24 & 0xF)), \\\n  ('0' + ((n)>>20 & 0xF)), \\\n  ('0' + ((n)>>16 & 0xF)), \\\n  ('0' + ((n)>>12 & 0xF)), \\\n  ('0' + ((n)>>8  & 0xF)), \\\n  ('0' + ((n)>>4  & 0xF)), \\\n  ('0' + ((n)     & 0xF))\n\n/* Construct a string literal encoding the version number components. */\n#ifdef COMPILER_VERSION_MAJOR\nchar const info_version[] = {\n  'I', 'N', 'F', 'O', ':',\n  'c','o','m','p','i','l','e','r','_','v','e','r','s','i','o','n','[',\n  COMPILER_VERSION_MAJOR,\n# ifdef COMPILER_VERSION_MINOR\n  '.', COMPILER_VERSION_MINOR,\n#  ifdef COMPILER_VERSION_PATCH\n   '.', COMPILER_VERSION_PATCH,\n#   ifdef COMPILER_VERSION_TWEAK\n    '.', COMPILER_VERSION_TWEAK,\n#   endif\n#  endif\n# endif\n  ']','\\0'}\n#endif\n\n/* Construct a string literal encoding the internal version number. */\n#ifdef COMPILER_VERSION_INTERNAL\nchar const info_version_internal[] = {\n  'I', 'N', 'F', 'O', ':',\n  'c','o','m','p','i','l','e','r','_','v','e','r','s','i','o','n','_',\n  'i','n','t','e','r','n','a','l','[',\n  COMPILER_VERSION_INTERNAL,']','\\0'}\n#endif\n\n/* Construct a string literal encoding the version number components. */\n#ifdef SIMULATE_VERSION_MAJOR\nchar const info_simulate_version[] = {\n  'I', 'N', 'F', 'O', ':',\n  's','i','m','u','l','a','t','e','_','v','e','r','s','i','o','n','[',\n  SIMULATE_VERSION_MAJOR,\n# ifdef SIMULATE_VERSION_MINOR\n  '.', SIMULATE_VERSION_MINOR,\n#  ifdef SIMULATE_VERSION_PATCH\n   '.', SIMULATE_VERSION_PATCH,\n#   ifdef SIMULATE_VERSION_TWEAK\n    '.', SIMULATE_VERSION_TWEAK,\n#   endif\n#  endif\n# endif\n  ']','\\0'}\n#endif\n\n/* Construct the string literal in pieces to prevent the source from\n   getting matched.  Store it in a pointer rather than an array\n   because some compilers will just produce instructions to fill the\n   array rather than assigning a pointer to a static array.  */\nchar const* info_platform = \"INFO\" \":\" \"platform[\" PLATFORM_ID \"]\"\nchar const* info_arch = \"INFO\" \":\" \"arch[\" ARCHITECTURE_ID \"]\"\n")
set(CMAKE_CXX_COMPILER_ID_RUN "1")
set(CMAKE_CXX_COMPILER_ID_TEST_FLAGS "-c--c++--ec++--target=arm-arm-none-eabi -mcpu=cortex-m3")
set(CMAKE_CXX_COMPILER_ID_TOOL_MATCH_INDEX "2")
set(CMAKE_CXX_COMPILER_ID_TOOL_MATCH_REGEX "\nLd[^\n]*(\n[ 	]+[^\n]*)*\n[ 	]+([^ 	\n\n]+)[^\n\n]*-o[^\n\n]*CompilerIdCXX/(\\./)?(CompilerIdCXX.(framework|xctest|build/[^ 	\n\n]+)/)?CompilerIdCXX[ 	\n\\\"]")
set(CMAKE_CXX_COMPILER_ID_VENDORS "IAR")
set(CMAKE_CXX_COMPILER_ID_VENDOR_REGEX_IAR "IAR .+ Compiler")
set(CMAKE_CXX_COMPILER_INIT "IAR .+ Compiler")
set(CMAKE_CXX_COMPILER_LIST "c++CCg++aCCclbccxlCclang++")
set(CMAKE_CXX_COMPILER_LOADED "1")
set(CMAKE_CXX_COMPILER_NAMES "c++")
set(CMAKE_CXX_COMPILER_PREDEFINES_COMMAND "/usr/bin/c++-dM-E-c/usr/share/cmake/Modules/CMakeCXXCompilerABI.cpp")
set(CMAKE_CXX_COMPILER_PRODUCED_FILES "a.out")
set(CMAKE_CXX_COMPILER_PRODUCED_OUTPUT "a.out")
set(CMAKE_CXX_COMPILER_RANLIB "/usr/bin/gcc-ranlib")
set(CMAKE_CXX_COMPILER_RANLIB "/usr/bin/gcc-ranlib")
set(CMAKE_CXX_COMPILER_SYSROOT "/usr/bin/gcc-ranlib")
set(CMAKE_CXX_COMPILER_VERSION "11.1.1")
set(CMAKE_CXX_COMPILER_VERSION_INTERNAL "11.1.1")
set(CMAKE_CXX_COMPILER_WORKS "TRUE")
set(CMAKE_CXX_COMPILER_WRAPPER "TRUE")
set(CMAKE_CXX_COMPILE_FEATURES "cxx_std_98cxx_template_template_parameterscxx_std_11cxx_alias_templatescxx_alignascxx_alignofcxx_attributescxx_auto_typecxx_constexprcxx_decltypecxx_decltype_incomplete_return_typescxx_default_function_template_argscxx_defaulted_functionscxx_defaulted_move_initializerscxx_delegating_constructorscxx_deleted_functionscxx_enum_forward_declarationscxx_explicit_conversionscxx_extended_friend_declarationscxx_extern_templatescxx_finalcxx_func_identifiercxx_generalized_initializerscxx_inheriting_constructorscxx_inline_namespacescxx_lambdascxx_local_type_template_argscxx_long_long_typecxx_noexceptcxx_nonstatic_member_initcxx_nullptrcxx_overridecxx_range_forcxx_raw_string_literalscxx_reference_qualified_functionscxx_right_angle_bracketscxx_rvalue_referencescxx_sizeof_membercxx_static_assertcxx_strong_enumscxx_thread_localcxx_trailing_return_typescxx_unicode_literalscxx_uniform_initializationcxx_unrestricted_unionscxx_user_literalscxx_variadic_macroscxx_variadic_templatescxx_std_14cxx_aggregate_default_initializerscxx_attribute_deprecatedcxx_binary_literalscxx_contextual_conversionscxx_decltype_autocxx_digit_separatorscxx_generic_lambdascxx_lambda_init_capturescxx_relaxed_constexprcxx_return_type_deductioncxx_variable_templatescxx_std_17cxx_std_20")
set(CMAKE_CXX_COMPILE_OBJECT "<CMAKE_CXX_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT> -c <SOURCE>")
set(CMAKE_CXX_COMPILE_OPTIONS_CREATE_PCH "-xc++-header-include<PCH_HEADER>")
set(CMAKE_CXX_COMPILE_OPTIONS_INVALID_PCH "-Winvalid-pch")
set(CMAKE_CXX_COMPILE_OPTIONS_IPO "-flto-fno-fat-lto-objects")
set(CMAKE_CXX_COMPILE_OPTIONS_PIC "-fPIC")
set(CMAKE_CXX_COMPILE_OPTIONS_PIE "-fPIE")
set(CMAKE_CXX_COMPILE_OPTIONS_SYSROOT "--sysroot=")
set(CMAKE_CXX_COMPILE_OPTIONS_USE_PCH "-include<PCH_HEADER>")
set(CMAKE_CXX_COMPILE_OPTIONS_VISIBILITY "-fvisibility=")
set(CMAKE_CXX_COMPILE_OPTIONS_VISIBILITY_INLINES_HIDDEN "-fvisibility-inlines-hidden")
set(CMAKE_CXX_CREATE_ASSEMBLY_SOURCE "<CMAKE_CXX_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -S <SOURCE> -o <ASSEMBLY_SOURCE>")
set(CMAKE_CXX_CREATE_PREPROCESSED_SOURCE "<CMAKE_CXX_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -E <SOURCE> > <PREPROCESSED_SOURCE>")
set(CMAKE_CXX_CREATE_SHARED_LIBRARY "<CMAKE_CXX_COMPILER> <CMAKE_SHARED_LIBRARY_CXX_FLAGS> <LANGUAGE_COMPILE_FLAGS> <LINK_FLAGS> <CMAKE_SHARED_LIBRARY_CREATE_CXX_FLAGS> <SONAME_FLAG><TARGET_SONAME> -o <TARGET> <OBJECTS> <LINK_LIBRARIES>")
set(CMAKE_CXX_CREATE_SHARED_MODULE "<CMAKE_CXX_COMPILER> <CMAKE_SHARED_LIBRARY_CXX_FLAGS> <LANGUAGE_COMPILE_FLAGS> <LINK_FLAGS> <CMAKE_SHARED_LIBRARY_CREATE_CXX_FLAGS> <SONAME_FLAG><TARGET_SONAME> -o <TARGET> <OBJECTS> <LINK_LIBRARIES>")
set(CMAKE_CXX_FLAGS "<CMAKE_CXX_COMPILER> <CMAKE_SHARED_LIBRARY_CXX_FLAGS> <LANGUAGE_COMPILE_FLAGS> <LINK_FLAGS> <CMAKE_SHARED_LIBRARY_CREATE_CXX_FLAGS> <SONAME_FLAG><TARGET_SONAME> -o <TARGET> <OBJECTS> <LINK_LIBRARIES>")
set(CMAKE_CXX_FLAGS_DEBUG "-g")
set(CMAKE_CXX_FLAGS_DEBUG_INIT " -g")
set(CMAKE_CXX_FLAGS_INIT "  ")
set(CMAKE_CXX_FLAGS_MINSIZEREL "-Os -DNDEBUG")
set(CMAKE_CXX_FLAGS_MINSIZEREL_INIT " -Os -DNDEBUG")
set(CMAKE_CXX_FLAGS_RELEASE "-O2 -DNDEBUG")
set(CMAKE_CXX_FLAGS_RELEASE_INIT " -O2 -DNDEBUG")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -g -DNDEBUG")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT " -O2 -g -DNDEBUG")
set(CMAKE_CXX_IGNORE_EXTENSIONS "inlhhppHPPHoOobjOBJdefDEFrcRC")
set(CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES "/usr/include/c++/11/usr/include/c++/11/x86_64-redhat-linux/usr/include/c++/11/backward/usr/lib/gcc/x86_64-redhat-linux/11/include/usr/local/include/usr/include")
set(CMAKE_CXX_IMPLICIT_LINK_DIRECTORIES "/usr/lib/gcc/x86_64-redhat-linux/11/usr/lib64/lib64/usr/lib")
set(CMAKE_CXX_IMPLICIT_LINK_FRAMEWORK_DIRECTORIES "/usr/lib/gcc/x86_64-redhat-linux/11/usr/lib64/lib64/usr/lib")
set(CMAKE_CXX_IMPLICIT_LINK_LIBRARIES "stdc++mgcc_sgcccgcc_sgcc")
set(CMAKE_CXX_INFORMATION_LOADED "1")
set(CMAKE_CXX_LIBRARY_ARCHITECTURE "1")
set(CMAKE_CXX_LINKER_PREFERENCE "30")
set(CMAKE_CXX_LINKER_PREFERENCE_PROPAGATES "1")
set(CMAKE_CXX_LINKER_WRAPPER_FLAG "-Wl,")
set(CMAKE_CXX_LINKER_WRAPPER_FLAG_SEP ",")
set(CMAKE_CXX_LINK_EXECUTABLE "<CMAKE_CXX_COMPILER> <FLAGS> <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
set(CMAKE_CXX_LINK_OPTIONS_NO_PIE "-no-pie")
set(CMAKE_CXX_LINK_OPTIONS_PIE "-fPIE-pie")
set(CMAKE_CXX_OUTPUT_EXTENSION ".o")
set(CMAKE_CXX_PLATFORM_ID "Linux")
set(CMAKE_CXX_SIMULATE_ID "Linux")
set(CMAKE_CXX_SIMULATE_VERSION "Linux")
set(CMAKE_CXX_SIZEOF_DATA_PTR "8")
set(CMAKE_CXX_SOURCE_FILE_EXTENSIONS "CMc++cccppcxxmmCPP")
set(CMAKE_CXX_STANDARD_COMPUTED_DEFAULT "17")
set(CMAKE_CXX_STANDARD_DEFAULT "17")
set(CMAKE_CXX_VERBOSE_FLAG "-v")
set(CMAKE_CXX_XCODE_ARCHS "-v")
set(CMAKE_C_ABI_COMPILED "TRUE")
set(CMAKE_C_ARCHIVE_APPEND "<CMAKE_AR> q <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_C_ARCHIVE_APPEND_IPO "\"/usr/bin/gcc-ar\" r <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_C_ARCHIVE_CREATE "<CMAKE_AR> qc <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_C_ARCHIVE_CREATE_IPO "\"/usr/bin/gcc-ar\" cr <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_C_ARCHIVE_FINISH "<CMAKE_RANLIB> <TARGET>")
set(CMAKE_C_ARCHIVE_FINISH_IPO "\"/usr/bin/gcc-ranlib\" <TARGET>")
set(CMAKE_C_CL_SHOWINCLUDES_PREFIX "\"/usr/bin/gcc-ranlib\" <TARGET>")
set(CMAKE_C_COMPILER "/usr/bin/cc")
set(CMAKE_C_COMPILER "/usr/bin/cc")
set(CMAKE_C_COMPILER_ABI "ELF")
set(CMAKE_C_COMPILER_AR "/usr/bin/gcc-ar")
set(CMAKE_C_COMPILER_AR "/usr/bin/gcc-ar")
set(CMAKE_C_COMPILER_ARCHITECTURE_ID "/usr/bin/gcc-ar")
set(CMAKE_C_COMPILER_ARG1 "/usr/bin/gcc-ar")
set(CMAKE_C_COMPILER_ENV_VAR "CC")
set(CMAKE_C_COMPILER_FRONTEND_VARIANT "CC")
set(CMAKE_C_COMPILER_ID "GNU")
set(CMAKE_C_COMPILER_ID_PLATFORM_CONTENT "#define STRINGIFY_HELPER(X) #X\n#define STRINGIFY(X) STRINGIFY_HELPER(X)\n\n/* Identify known platforms by name.  */\n#if defined(__linux) || defined(__linux__) || defined(linux)\n# define PLATFORM_ID \"Linux\"\n\n#elif defined(__CYGWIN__)\n# define PLATFORM_ID \"Cygwin\"\n\n#elif defined(__MINGW32__)\n# define PLATFORM_ID \"MinGW\"\n\n#elif defined(__APPLE__)\n# define PLATFORM_ID \"Darwin\"\n\n#elif defined(_WIN32) || defined(__WIN32__) || defined(WIN32)\n# define PLATFORM_ID \"Windows\"\n\n#elif defined(__FreeBSD__) || defined(__FreeBSD)\n# define PLATFORM_ID \"FreeBSD\"\n\n#elif defined(__NetBSD__) || defined(__NetBSD)\n# define PLATFORM_ID \"NetBSD\"\n\n#elif defined(__OpenBSD__) || defined(__OPENBSD)\n# define PLATFORM_ID \"OpenBSD\"\n\n#elif defined(__sun) || defined(sun)\n# define PLATFORM_ID \"SunOS\"\n\n#elif defined(_AIX) || defined(__AIX) || defined(__AIX__) || defined(__aix) || defined(__aix__)\n# define PLATFORM_ID \"AIX\"\n\n#elif defined(__hpux) || defined(__hpux__)\n# define PLATFORM_ID \"HP-UX\"\n\n#elif defined(__HAIKU__)\n# define PLATFORM_ID \"Haiku\"\n\n#elif defined(__BeOS) || defined(__BEOS__) || defined(_BEOS)\n# define PLATFORM_ID \"BeOS\"\n\n#elif defined(__QNX__) || defined(__QNXNTO__)\n# define PLATFORM_ID \"QNX\"\n\n#elif defined(__tru64) || defined(_tru64) || defined(__TRU64__)\n# define PLATFORM_ID \"Tru64\"\n\n#elif defined(__riscos) || defined(__riscos__)\n# define PLATFORM_ID \"RISCos\"\n\n#elif defined(__sinix) || defined(__sinix__) || defined(__SINIX__)\n# define PLATFORM_ID \"SINIX\"\n\n#elif defined(__UNIX_SV__)\n# define PLATFORM_ID \"UNIX_SV\"\n\n#elif defined(__bsdos__)\n# define PLATFORM_ID \"BSDOS\"\n\n#elif defined(_MPRAS) || defined(MPRAS)\n# define PLATFORM_ID \"MP-RAS\"\n\n#elif defined(__osf) || defined(__osf__)\n# define PLATFORM_ID \"OSF1\"\n\n#elif defined(_SCO_SV) || defined(SCO_SV) || defined(sco_sv)\n# define PLATFORM_ID \"SCO_SV\"\n\n#elif defined(__ultrix) || defined(__ultrix__) || defined(_ULTRIX)\n# define PLATFORM_ID \"ULTRIX\"\n\n#elif defined(__XENIX__) || defined(_XENIX) || defined(XENIX)\n# define PLATFORM_ID \"Xenix\"\n\n#elif defined(__WATCOMC__)\n# if defined(__LINUX__)\n#  define PLATFORM_ID \"Linux\"\n\n# elif defined(__DOS__)\n#  define PLATFORM_ID \"DOS\"\n\n# elif defined(__OS2__)\n#  define PLATFORM_ID \"OS2\"\n\n# elif defined(__WINDOWS__)\n#  define PLATFORM_ID \"Windows3x\"\n\n# elif defined(__VXWORKS__)\n#  define PLATFORM_ID \"VxWorks\"\n\n# else /* unknown platform */\n#  define PLATFORM_ID\n# endif\n\n#elif defined(__INTEGRITY)\n# if defined(INT_178B)\n#  define PLATFORM_ID \"Integrity178\"\n\n# else /* regular Integrity */\n#  define PLATFORM_ID \"Integrity\"\n# endif\n\n#else /* unknown platform */\n# define PLATFORM_ID\n\n#endif\n\n/* For windows compilers MSVC and Intel we can determine\n   the architecture of the compiler being used.  This is because\n   the compilers do not have flags that can change the architecture,\n   but rather depend on which compiler is being used\n*/\n#if defined(_WIN32) && defined(_MSC_VER)\n# if defined(_M_IA64)\n#  define ARCHITECTURE_ID \"IA64\"\n\n# elif defined(_M_X64) || defined(_M_AMD64)\n#  define ARCHITECTURE_ID \"x64\"\n\n# elif defined(_M_IX86)\n#  define ARCHITECTURE_ID \"X86\"\n\n# elif defined(_M_ARM64)\n#  define ARCHITECTURE_ID \"ARM64\"\n\n# elif defined(_M_ARM)\n#  if _M_ARM == 4\n#   define ARCHITECTURE_ID \"ARMV4I\"\n#  elif _M_ARM == 5\n#   define ARCHITECTURE_ID \"ARMV5I\"\n#  else\n#   define ARCHITECTURE_ID \"ARMV\" STRINGIFY(_M_ARM)\n#  endif\n\n# elif defined(_M_MIPS)\n#  define ARCHITECTURE_ID \"MIPS\"\n\n# elif defined(_M_SH)\n#  define ARCHITECTURE_ID \"SHx\"\n\n# else /* unknown architecture */\n#  define ARCHITECTURE_ID \"\"\n# endif\n\n#elif defined(__WATCOMC__)\n# if defined(_M_I86)\n#  define ARCHITECTURE_ID \"I86\"\n\n# elif defined(_M_IX86)\n#  define ARCHITECTURE_ID \"X86\"\n\n# else /* unknown architecture */\n#  define ARCHITECTURE_ID \"\"\n# endif\n\n#elif defined(__IAR_SYSTEMS_ICC__) || defined(__IAR_SYSTEMS_ICC)\n# if defined(__ICCARM__)\n#  define ARCHITECTURE_ID \"ARM\"\n\n# elif defined(__ICCRX__)\n#  define ARCHITECTURE_ID \"RX\"\n\n# elif defined(__ICCRH850__)\n#  define ARCHITECTURE_ID \"RH850\"\n\n# elif defined(__ICCRL78__)\n#  define ARCHITECTURE_ID \"RL78\"\n\n# elif defined(__ICCRISCV__)\n#  define ARCHITECTURE_ID \"RISCV\"\n\n# elif defined(__ICCAVR__)\n#  define ARCHITECTURE_ID \"AVR\"\n\n# elif defined(__ICC430__)\n#  define ARCHITECTURE_ID \"MSP430\"\n\n# elif defined(__ICCV850__)\n#  define ARCHITECTURE_ID \"V850\"\n\n# elif defined(__ICC8051__)\n#  define ARCHITECTURE_ID \"8051\"\n\n# else /* unknown architecture */\n#  define ARCHITECTURE_ID \"\"\n# endif\n\n#elif defined(__ghs__)\n# if defined(__PPC64__)\n#  define ARCHITECTURE_ID \"PPC64\"\n\n# elif defined(__ppc__)\n#  define ARCHITECTURE_ID \"PPC\"\n\n# elif defined(__ARM__)\n#  define ARCHITECTURE_ID \"ARM\"\n\n# elif defined(__x86_64__)\n#  define ARCHITECTURE_ID \"x64\"\n\n# elif defined(__i386__)\n#  define ARCHITECTURE_ID \"X86\"\n\n# else /* unknown architecture */\n#  define ARCHITECTURE_ID \"\"\n# endif\n\n#elif defined(__TI_COMPILER_VERSION__)\n# if defined(__TI_ARM__)\n#  define ARCHITECTURE_ID \"ARM\"\n\n# elif defined(__MSP430__)\n#  define ARCHITECTURE_ID \"MSP430\"\n\n# elif defined(__TMS320C28XX__)\n#  define ARCHITECTURE_ID \"TMS320C28x\"\n\n# elif defined(__TMS320C6X__) || defined(_TMS320C6X)\n#  define ARCHITECTURE_ID \"TMS320C6x\"\n\n# else /* unknown architecture */\n#  define ARCHITECTURE_ID \"\"\n# endif\n\n#else\n#  define ARCHITECTURE_ID\n#endif\n\n/* Convert integer to decimal digit literals.  */\n#define DEC(n)                   \\\n  ('0' + (((n) / 10000000)%10)), \\\n  ('0' + (((n) / 1000000)%10)),  \\\n  ('0' + (((n) / 100000)%10)),   \\\n  ('0' + (((n) / 10000)%10)),    \\\n  ('0' + (((n) / 1000)%10)),     \\\n  ('0' + (((n) / 100)%10)),      \\\n  ('0' + (((n) / 10)%10)),       \\\n  ('0' +  ((n) % 10))\n\n/* Convert integer to hex digit literals.  */\n#define HEX(n)             \\\n  ('0' + ((n)>>28 & 0xF)), \\\n  ('0' + ((n)>>24 & 0xF)), \\\n  ('0' + ((n)>>20 & 0xF)), \\\n  ('0' + ((n)>>16 & 0xF)), \\\n  ('0' + ((n)>>12 & 0xF)), \\\n  ('0' + ((n)>>8  & 0xF)), \\\n  ('0' + ((n)>>4  & 0xF)), \\\n  ('0' + ((n)     & 0xF))\n\n/* Construct a string literal encoding the version number components. */\n#ifdef COMPILER_VERSION_MAJOR\nchar const info_version[] = {\n  'I', 'N', 'F', 'O', ':',\n  'c','o','m','p','i','l','e','r','_','v','e','r','s','i','o','n','[',\n  COMPILER_VERSION_MAJOR,\n# ifdef COMPILER_VERSION_MINOR\n  '.', COMPILER_VERSION_MINOR,\n#  ifdef COMPILER_VERSION_PATCH\n   '.', COMPILER_VERSION_PATCH,\n#   ifdef COMPILER_VERSION_TWEAK\n    '.', COMPILER_VERSION_TWEAK,\n#   endif\n#  endif\n# endif\n  ']','\\0'}\n#endif\n\n/* Construct a string literal encoding the internal version number. */\n#ifdef COMPILER_VERSION_INTERNAL\nchar const info_version_internal[] = {\n  'I', 'N', 'F', 'O', ':',\n  'c','o','m','p','i','l','e','r','_','v','e','r','s','i','o','n','_',\n  'i','n','t','e','r','n','a','l','[',\n  COMPILER_VERSION_INTERNAL,']','\\0'}\n#endif\n\n/* Construct a string literal encoding the version number components. */\n#ifdef SIMULATE_VERSION_MAJOR\nchar const info_simulate_version[] = {\n  'I', 'N', 'F', 'O', ':',\n  's','i','m','u','l','a','t','e','_','v','e','r','s','i','o','n','[',\n  SIMULATE_VERSION_MAJOR,\n# ifdef SIMULATE_VERSION_MINOR\n  '.', SIMULATE_VERSION_MINOR,\n#  ifdef SIMULATE_VERSION_PATCH\n   '.', SIMULATE_VERSION_PATCH,\n#   ifdef SIMULATE_VERSION_TWEAK\n    '.', SIMULATE_VERSION_TWEAK,\n#   endif\n#  endif\n# endif\n  ']','\\0'}\n#endif\n\n/* Construct the string literal in pieces to prevent the source from\n   getting matched.  Store it in a pointer rather than an array\n   because some compilers will just produce instructions to fill the\n   array rather than assigning a pointer to a static array.  */\nchar const* info_platform = \"INFO\" \":\" \"platform[\" PLATFORM_ID \"]\"\nchar const* info_arch = \"INFO\" \":\" \"arch[\" ARCHITECTURE_ID \"]\"\n")
set(CMAKE_C_COMPILER_ID_RUN "1")
set(CMAKE_C_COMPILER_ID_TEST_FLAGS "-c-Aa-D__CLASSIC_C__--target=arm-arm-none-eabi -mcpu=cortex-m3")
set(CMAKE_C_COMPILER_ID_TOOL_MATCH_INDEX "2")
set(CMAKE_C_COMPILER_ID_TOOL_MATCH_REGEX "\nLd[^\n]*(\n[ 	]+[^\n]*)*\n[ 	]+([^ 	\n\n]+)[^\n\n]*-o[^\n\n]*CompilerIdC/(\\./)?(CompilerIdC.(framework|xctest|build/[^ 	\n\n]+)/)?CompilerIdC[ 	\n\\\"]")
set(CMAKE_C_COMPILER_ID_VENDORS "IAR")
set(CMAKE_C_COMPILER_ID_VENDOR_REGEX_IAR "IAR .+ Compiler")
set(CMAKE_C_COMPILER_INIT "IAR .+ Compiler")
set(CMAKE_C_COMPILER_LIST "ccgccclbccxlcclang")
set(CMAKE_C_COMPILER_LOADED "1")
set(CMAKE_C_COMPILER_NAMES "cc")
set(CMAKE_C_COMPILER_PREDEFINES_COMMAND "/usr/bin/cc-dM-E-c/usr/share/cmake/Modules/CMakeCXXCompilerABI.cpp")
set(CMAKE_C_COMPILER_PRODUCED_FILES "a.out")
set(CMAKE_C_COMPILER_PRODUCED_OUTPUT "a.out")
set(CMAKE_C_COMPILER_RANLIB "/usr/bin/gcc-ranlib")
set(CMAKE_C_COMPILER_RANLIB "/usr/bin/gcc-ranlib")
set(CMAKE_C_COMPILER_SYSROOT "/usr/bin/gcc-ranlib")
set(CMAKE_C_COMPILER_VERSION "11.1.1")
set(CMAKE_C_COMPILER_VERSION_INTERNAL "11.1.1")
set(CMAKE_C_COMPILER_WORKS "TRUE")
set(CMAKE_C_COMPILER_WRAPPER "TRUE")
set(CMAKE_C_COMPILE_FEATURES "c_std_90c_function_prototypesc_std_99c_restrictc_variadic_macrosc_std_11c_static_assert")
set(CMAKE_C_COMPILE_OBJECT "<CMAKE_C_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT> -c <SOURCE>")
set(CMAKE_C_COMPILE_OPTIONS_CREATE_PCH "-xc-header-include<PCH_HEADER>")
set(CMAKE_C_COMPILE_OPTIONS_INVALID_PCH "-Winvalid-pch")
set(CMAKE_C_COMPILE_OPTIONS_IPO "-flto-fno-fat-lto-objects")
set(CMAKE_C_COMPILE_OPTIONS_PIC "-fPIC")
set(CMAKE_C_COMPILE_OPTIONS_PIE "-fPIE")
set(CMAKE_C_COMPILE_OPTIONS_SYSROOT "--sysroot=")
set(CMAKE_C_COMPILE_OPTIONS_USE_PCH "-include<PCH_HEADER>")
set(CMAKE_C_COMPILE_OPTIONS_VISIBILITY "-fvisibility=")
set(CMAKE_C_CREATE_ASSEMBLY_SOURCE "<CMAKE_C_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -S <SOURCE> -o <ASSEMBLY_SOURCE>")
set(CMAKE_C_CREATE_PREPROCESSED_SOURCE "<CMAKE_C_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -E <SOURCE> > <PREPROCESSED_SOURCE>")
set(CMAKE_C_CREATE_SHARED_LIBRARY "<CMAKE_C_COMPILER> <CMAKE_SHARED_LIBRARY_C_FLAGS> <LANGUAGE_COMPILE_FLAGS> <LINK_FLAGS> <CMAKE_SHARED_LIBRARY_CREATE_C_FLAGS> <SONAME_FLAG><TARGET_SONAME> -o <TARGET> <OBJECTS> <LINK_LIBRARIES>")
set(CMAKE_C_CREATE_SHARED_MODULE "<CMAKE_C_COMPILER> <CMAKE_SHARED_LIBRARY_C_FLAGS> <LANGUAGE_COMPILE_FLAGS> <LINK_FLAGS> <CMAKE_SHARED_LIBRARY_CREATE_C_FLAGS> <SONAME_FLAG><TARGET_SONAME> -o <TARGET> <OBJECTS> <LINK_LIBRARIES>")
set(CMAKE_C_FLAGS "<CMAKE_C_COMPILER> <CMAKE_SHARED_LIBRARY_C_FLAGS> <LANGUAGE_COMPILE_FLAGS> <LINK_FLAGS> <CMAKE_SHARED_LIBRARY_CREATE_C_FLAGS> <SONAME_FLAG><TARGET_SONAME> -o <TARGET> <OBJECTS> <LINK_LIBRARIES>")
set(CMAKE_C_FLAGS_DEBUG "-g")
set(CMAKE_C_FLAGS_DEBUG_INIT " -g")
set(CMAKE_C_FLAGS_INIT "  ")
set(CMAKE_C_FLAGS_MINSIZEREL "-Os -DNDEBUG")
set(CMAKE_C_FLAGS_MINSIZEREL_INIT " -Os -DNDEBUG")
set(CMAKE_C_FLAGS_RELEASE "-O2 -DNDEBUG")
set(CMAKE_C_FLAGS_RELEASE_INIT " -O2 -DNDEBUG")
set(CMAKE_C_FLAGS_RELWITHDEBINFO "-O2 -g -DNDEBUG")
set(CMAKE_C_FLAGS_RELWITHDEBINFO_INIT " -O2 -g -DNDEBUG")
set(CMAKE_C_IGNORE_EXTENSIONS "hHoOobjOBJdefDEFrcRC")
set(CMAKE_C_IMPLICIT_INCLUDE_DIRECTORIES "/usr/lib/gcc/x86_64-redhat-linux/11/include/usr/local/include/usr/include")
set(CMAKE_C_IMPLICIT_LINK_DIRECTORIES "/usr/lib/gcc/x86_64-redhat-linux/11/usr/lib64/lib64/usr/lib")
set(CMAKE_C_IMPLICIT_LINK_FRAMEWORK_DIRECTORIES "/usr/lib/gcc/x86_64-redhat-linux/11/usr/lib64/lib64/usr/lib")
set(CMAKE_C_IMPLICIT_LINK_LIBRARIES "gccgcc_scgccgcc_s")
set(CMAKE_C_INFORMATION_LOADED "1")
set(CMAKE_C_LIBRARY_ARCHITECTURE "1")
set(CMAKE_C_LINKER_PREFERENCE "10")
set(CMAKE_C_LINKER_WRAPPER_FLAG "-Wl,")
set(CMAKE_C_LINKER_WRAPPER_FLAG_SEP ",")
set(CMAKE_C_LINK_EXECUTABLE "<CMAKE_C_COMPILER> <FLAGS> <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
set(CMAKE_C_LINK_OPTIONS_NO_PIE "-no-pie")
set(CMAKE_C_LINK_OPTIONS_PIE "-fPIE-pie")
set(CMAKE_C_OUTPUT_EXTENSION ".o")
set(CMAKE_C_PLATFORM_ID "Linux")
set(CMAKE_C_SIMULATE_ID "Linux")
set(CMAKE_C_SIMULATE_VERSION "Linux")
set(CMAKE_C_SIZEOF_DATA_PTR "8")
set(CMAKE_C_SOURCE_FILE_EXTENSIONS "cm")
set(CMAKE_C_STANDARD_COMPUTED_DEFAULT "11")
set(CMAKE_C_STANDARD_DEFAULT "11")
set(CMAKE_C_VERBOSE_FLAG "-v")
set(CMAKE_C_XCODE_ARCHS "-v")
set(CMAKE_DEPFILE_FLAGS_C "-MD -MT <OBJECT> -MF <DEPFILE>")
set(CMAKE_DEPFILE_FLAGS_CXX "-MD -MT <OBJECT> -MF <DEPFILE>")
set(CMAKE_DLLTOOL "-MD -MT <OBJECT> -MF <DEPFILE>")
set(CMAKE_DL_LIBS "dl")
set(CMAKE_EDIT_COMMAND "/usr/bin/ccmake")
set(CMAKE_EFFECTIVE_SYSTEM_NAME "Linux")
set(CMAKE_EXECUTABLE_FORMAT "ELF")
set(CMAKE_EXECUTABLE_RPATH_LINK_CXX_FLAG "-Wl,-rpath-link,")
set(CMAKE_EXECUTABLE_RPATH_LINK_C_FLAG "-Wl,-rpath-link,")
set(CMAKE_EXECUTABLE_RUNTIME_CXX_FLAG "-Wl,-rpath,")
set(CMAKE_EXECUTABLE_RUNTIME_CXX_FLAG_SEP ":")
set(CMAKE_EXECUTABLE_RUNTIME_C_FLAG "-Wl,-rpath,")
set(CMAKE_EXECUTABLE_RUNTIME_C_FLAG_SEP ":")
set(CMAKE_EXECUTABLE_SUFFIX ":")
set(CMAKE_EXE_EXPORTS_CXX_FLAG "-Wl,--export-dynamic")
set(CMAKE_EXE_EXPORTS_C_FLAG "-Wl,--export-dynamic")
set(CMAKE_EXE_LINKER_FLAGS "-Wl,--export-dynamic")
set(CMAKE_EXE_LINKER_FLAGS_DEBUG "-Wl,--export-dynamic")
set(CMAKE_EXE_LINKER_FLAGS_INIT "  ")
set(CMAKE_EXE_LINKER_FLAGS_MINSIZEREL "  ")
set(CMAKE_EXE_LINKER_FLAGS_RELEASE "  ")
set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "  ")
set(CMAKE_EXE_LINK_DYNAMIC_CXX_FLAGS "-Wl,-Bdynamic")
set(CMAKE_EXE_LINK_DYNAMIC_C_FLAGS "-Wl,-Bdynamic")
set(CMAKE_EXE_LINK_STATIC_CXX_FLAGS "-Wl,-Bstatic")
set(CMAKE_EXE_LINK_STATIC_C_FLAGS "-Wl,-Bstatic")
set(CMAKE_EXPORT_COMPILE_COMMANDS "-Wl,-Bstatic")
set(CMAKE_EXTRA_GENERATOR "-Wl,-Bstatic")
set(CMAKE_FILES_DIRECTORY "/CMakeFiles")
set(CMAKE_FIND_LIBRARY_PREFIXES "lib")
set(CMAKE_FIND_LIBRARY_SUFFIXES ".so.a")
set(CMAKE_GENERATOR "Unix Makefiles")
set(CMAKE_GENERATOR_INSTANCE "Unix Makefiles")
set(CMAKE_GENERATOR_PLATFORM "Unix Makefiles")
set(CMAKE_GENERATOR_TOOLSET "Unix Makefiles")
set(CMAKE_HOME_DIRECTORY "/home/fulup/Workspace/AFB-binder/sec-gate-oidc")
set(CMAKE_HOST_SYSTEM "Linux-5.11.17-300.fc34.x86_64")
set(CMAKE_HOST_SYSTEM_NAME "Linux")
set(CMAKE_HOST_SYSTEM_PROCESSOR "x86_64")
set(CMAKE_HOST_SYSTEM_VERSION "5.11.17-300.fc34.x86_64")
set(CMAKE_HOST_UNIX "1")
set(CMAKE_INCLUDE_FLAG_C "-I")
set(CMAKE_INCLUDE_FLAG_CXX "-I")
set(CMAKE_INCLUDE_SYSTEM_FLAG_C "-isystem ")
set(CMAKE_INCLUDE_SYSTEM_FLAG_CXX "-isystem ")
set(CMAKE_INSTALL_BINDIR "bin")
set(CMAKE_INSTALL_DATADIR "share")
set(CMAKE_INSTALL_DATADIR "share")
set(CMAKE_INSTALL_DATAROOTDIR "share")
set(CMAKE_INSTALL_DEFAULT_COMPONENT_NAME "Unspecified")
set(CMAKE_INSTALL_DOCDIR "share/doc/afb-sgate-oidc")
set(CMAKE_INSTALL_DOCDIR "share/doc/afb-sgate-oidc")
set(CMAKE_INSTALL_FULL_BINDIR "/usr/local/bin")
set(CMAKE_INSTALL_FULL_DATADIR "/usr/local/share")
set(CMAKE_INSTALL_FULL_DATAROOTDIR "/usr/local/share")
set(CMAKE_INSTALL_FULL_DOCDIR "/usr/local/share/doc/afb-sgate-oidc")
set(CMAKE_INSTALL_FULL_INCLUDEDIR "/usr/local/include")
set(CMAKE_INSTALL_FULL_INFODIR "/usr/local/share/info")
set(CMAKE_INSTALL_FULL_LIBDIR "/usr/local/lib64")
set(CMAKE_INSTALL_FULL_LIBEXECDIR "/usr/local/libexec")
set(CMAKE_INSTALL_FULL_LOCALEDIR "/usr/local/share/locale")
set(CMAKE_INSTALL_FULL_LOCALSTATEDIR "/usr/local/var")
set(CMAKE_INSTALL_FULL_MANDIR "/usr/local/share/man")
set(CMAKE_INSTALL_FULL_OLDINCLUDEDIR "/usr/include")
set(CMAKE_INSTALL_FULL_RUNSTATEDIR "/usr/local/var/run")
set(CMAKE_INSTALL_FULL_SBINDIR "/usr/local/sbin")
set(CMAKE_INSTALL_FULL_SHAREDSTATEDIR "/usr/local/com")
set(CMAKE_INSTALL_FULL_SYSCONFDIR "/usr/local/etc")
set(CMAKE_INSTALL_INCLUDEDIR "include")
set(CMAKE_INSTALL_INFODIR "share/info")
set(CMAKE_INSTALL_INFODIR "share/info")
set(CMAKE_INSTALL_LIBDIR "lib64")
set(CMAKE_INSTALL_LIBEXECDIR "libexec")
set(CMAKE_INSTALL_LOCALEDIR "share/locale")
set(CMAKE_INSTALL_LOCALEDIR "share/locale")
set(CMAKE_INSTALL_LOCALSTATEDIR "var")
set(CMAKE_INSTALL_MANDIR "share/man")
set(CMAKE_INSTALL_MANDIR "share/man")
set(CMAKE_INSTALL_OLDINCLUDEDIR "/usr/include")
set(CMAKE_INSTALL_PREFIX "/usr/local")
set(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT "1")
set(CMAKE_INSTALL_RUNSTATEDIR "var/run")
set(CMAKE_INSTALL_RUNSTATEDIR "var/run")
set(CMAKE_INSTALL_SBINDIR "sbin")
set(CMAKE_INSTALL_SHAREDSTATEDIR "com")
set(CMAKE_INSTALL_SO_NO_EXE "com")
set(CMAKE_INSTALL_SO_NO_EXE "com")
set(CMAKE_INSTALL_SYSCONFDIR "etc")
set(CMAKE_INTERNAL_PLATFORM_ABI "ELF")
set(CMAKE_LIBRARY_ARCHITECTURE_REGEX "[a-z0-9_]+(-[a-z0-9_]+)?-linux-gnu[a-z0-9_]*")
set(CMAKE_LIBRARY_PATH_FLAG "-L")
set(CMAKE_LIBRARY_PATH_TERMINATOR "-L")
set(CMAKE_LINKER "/usr/bin/ld")
set(CMAKE_LINKER "/usr/bin/ld")
set(CMAKE_LINK_LIBRARY_FLAG "-l")
set(CMAKE_LINK_LIBRARY_SUFFIX "-l")
set(CMAKE_MAJOR_VERSION "3")
set(CMAKE_MAKE_PROGRAM "/usr/bin/gmake")
set(CMAKE_MATCH_0 "/usr/bin/gmake")
set(CMAKE_MATCH_1 "/usr/bin/gmake")
set(CMAKE_MATCH_2 "/usr/bin/gmake")
set(CMAKE_MATCH_COUNT "/usr/bin/gmake")
set(CMAKE_MINIMUM_REQUIRED_VERSION "3.6")
set(CMAKE_MINOR_VERSION "19")
set(CMAKE_MODULE_LINKER_FLAGS "19")
set(CMAKE_MODULE_LINKER_FLAGS_DEBUG "19")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "  ")
set(CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL "  ")
set(CMAKE_MODULE_LINKER_FLAGS_RELEASE "  ")
set(CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO "  ")
set(CMAKE_MT "  ")
set(CMAKE_NM "/usr/bin/nm")
set(CMAKE_OBJCOPY "/usr/bin/objcopy")
set(CMAKE_OBJDUMP "/usr/bin/objdump")
set(CMAKE_PARENT_LIST_FILE "/usr/share/cmake/Modules/CMakeAfbTemplates/cmake/common.cmake")
set(CMAKE_PATCH_VERSION "7")
set(CMAKE_PCH_EXTENSION ".gch")
set(CMAKE_PCH_PROLOGUE "#pragma GCC system_header")
set(CMAKE_PLATFORM_IMPLICIT_LINK_DIRECTORIES "/lib/lib32/lib64/usr/lib/usr/lib32/usr/lib64")
set(CMAKE_PLATFORM_INFO_DIR "/home/fulup/Workspace/AFB-binder/sec-gate-oidc/build/CMakeFiles/3.19.7")
set(CMAKE_PLATFORM_INFO_INITIALIZED "1")
set(CMAKE_PLATFORM_USES_PATH_WHEN_NO_SONAME "1")
set(CMAKE_POSITION_INDEPENDENT_CODE "ON")
set(CMAKE_PREFIX_PATH "/usr/local/lib64/pkgconfig/usr/local/lib/pkgconfig")
set(CMAKE_PROJECT_DESCRIPTION "Provide authentication through OpenID")
set(CMAKE_PROJECT_HOMEPAGE_URL "https://github.com/redpesk-common/afb-oidc")
set(CMAKE_PROJECT_NAME "afb-sgate-oidc")
set(CMAKE_PROJECT_VERSION "1.0")
set(CMAKE_PROJECT_VERSION_MAJOR "1")
set(CMAKE_PROJECT_VERSION_MINOR "1")
set(CMAKE_PROJECT_VERSION_PATCH "1")
set(CMAKE_PROJECT_VERSION_TWEAK "1")
set(CMAKE_RANLIB "/usr/bin/ranlib")
set(CMAKE_RANLIB "/usr/bin/ranlib")
set(CMAKE_READELF "/usr/bin/readelf")
set(CMAKE_ROOT "/usr/share/cmake")
set(CMAKE_SHARED_LIBRARY_CREATE_CXX_FLAGS "-shared")
set(CMAKE_SHARED_LIBRARY_CREATE_C_FLAGS "-shared")
set(CMAKE_SHARED_LIBRARY_CXX_FLAGS "-fPIC")
set(CMAKE_SHARED_LIBRARY_C_FLAGS "-fPIC")
set(CMAKE_SHARED_LIBRARY_LINK_CXX_FLAGS "-rdynamic")
set(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS "-rdynamic")
set(CMAKE_SHARED_LIBRARY_LINK_DYNAMIC_CXX_FLAGS "-Wl,-Bdynamic")
set(CMAKE_SHARED_LIBRARY_LINK_DYNAMIC_C_FLAGS "-Wl,-Bdynamic")
set(CMAKE_SHARED_LIBRARY_LINK_STATIC_CXX_FLAGS "-Wl,-Bstatic")
set(CMAKE_SHARED_LIBRARY_LINK_STATIC_C_FLAGS "-Wl,-Bstatic")
set(CMAKE_SHARED_LIBRARY_PREFIX "lib")
set(CMAKE_SHARED_LIBRARY_RPATH_LINK_CXX_FLAG "-Wl,-rpath-link,")
set(CMAKE_SHARED_LIBRARY_RPATH_LINK_C_FLAG "-Wl,-rpath-link,")
set(CMAKE_SHARED_LIBRARY_RPATH_ORIGIN_TOKEN "$ORIGIN")
set(CMAKE_SHARED_LIBRARY_RUNTIME_CXX_FLAG "-Wl,-rpath,")
set(CMAKE_SHARED_LIBRARY_RUNTIME_CXX_FLAG_SEP ":")
set(CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG "-Wl,-rpath,")
set(CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG_SEP ":")
set(CMAKE_SHARED_LIBRARY_SONAME_CXX_FLAG "-Wl,-soname,")
set(CMAKE_SHARED_LIBRARY_SONAME_C_FLAG "-Wl,-soname,")
set(CMAKE_SHARED_LIBRARY_SUFFIX ".so")
set(CMAKE_SHARED_LINKER_FLAGS ".so")
set(CMAKE_SHARED_LINKER_FLAGS_DEBUG ".so")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "  ")
set(CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL "  ")
set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "  ")
set(CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO "  ")
set(CMAKE_SHARED_MODULE_CREATE_CXX_FLAGS "-shared")
set(CMAKE_SHARED_MODULE_CREATE_C_FLAGS "-shared")
set(CMAKE_SHARED_MODULE_CXX_FLAGS "-fPIC")
set(CMAKE_SHARED_MODULE_C_FLAGS "-fPIC")
set(CMAKE_SHARED_MODULE_LINK_DYNAMIC_CXX_FLAGS "-Wl,-Bdynamic")
set(CMAKE_SHARED_MODULE_LINK_DYNAMIC_C_FLAGS "-Wl,-Bdynamic")
set(CMAKE_SHARED_MODULE_LINK_STATIC_CXX_FLAGS "-Wl,-Bstatic")
set(CMAKE_SHARED_MODULE_LINK_STATIC_C_FLAGS "-Wl,-Bstatic")
set(CMAKE_SHARED_MODULE_PREFIX "lib")
set(CMAKE_SHARED_MODULE_SUFFIX ".so")
set(CMAKE_SIZEOF_VOID_P "8")
set(CMAKE_SKIP_INSTALL_RPATH "8")
set(CMAKE_SKIP_RPATH "8")
set(CMAKE_SOURCE_DIR "/home/fulup/Workspace/AFB-binder/sec-gate-oidc")
set(CMAKE_STATIC_LIBRARY_PREFIX "lib")
set(CMAKE_STATIC_LIBRARY_SUFFIX ".a")
set(CMAKE_STATIC_LINKER_FLAGS ".a")
set(CMAKE_STATIC_LINKER_FLAGS_DEBUG ".a")
set(CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL ".a")
set(CMAKE_STATIC_LINKER_FLAGS_RELEASE ".a")
set(CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO ".a")
set(CMAKE_STRIP "/usr/bin/strip")
set(CMAKE_SYSTEM "Linux-5.11.17-300.fc34.x86_64")
set(CMAKE_SYSTEM_INCLUDE_PATH "/usr/include/X11")
set(CMAKE_SYSTEM_INFO_FILE "Platform/Linux")
set(CMAKE_SYSTEM_LIBRARY_PATH "/usr/lib/X11")
set(CMAKE_SYSTEM_LOADED "1")
set(CMAKE_SYSTEM_NAME "Linux")
set(CMAKE_SYSTEM_PREFIX_PATH "/usr/local/usr//usr/usr/local/usr/X11R6/usr/pkg/opt")
set(CMAKE_SYSTEM_PROCESSOR "x86_64")
set(CMAKE_SYSTEM_SPECIFIC_INFORMATION_LOADED "1")
set(CMAKE_SYSTEM_SPECIFIC_INITIALIZE_LOADED "1")
set(CMAKE_SYSTEM_VERSION "5.11.17-300.fc34.x86_64")
set(CMAKE_TWEAK_VERSION "5.11.17-300.fc34.x86_64")
set(CMAKE_UNAME "/usr/bin/uname")
set(CMAKE_VERBOSE_MAKEFILE "/usr/bin/uname")
set(CMAKE_VERSION "3.19.7")
set(CMP0048 "1")
set(COMMIT_HASH "eb68976")
set(COMPILER_BASENAME "c++")
set(COMPILE_OPTIONS "-Wall-Wextra-Wconversion-Wno-unused-parameter-Wno-sign-compare-Wno-sign-conversion-Wno-uninitialized-Werror=implicit-function-declaration-ffunction-sections-fdata-sections-fPIC")
set(COMPILE_OPTIONS_CLANG "-Werror=uninitialized")
set(COMPILE_OPTIONS_GNU "-Werror=maybe-uninitialized")
set(CONTROL_CONFIG_PATH "/home/fulup/Workspace/AFB-binder/sec-gate-oidc/conf.d/project/etc:/home/fulup/Workspace/AFB-binder/sec-gate-oidc/build/package/etc:/usr/local/afb-sgate-oidc/etc")
set(COVERAGE_COMPILE_OPTIONS "-g-O0--coverage")
set(C_COMPILE_OPTIONS "-g-O0--coverage")
set(CacheForScript "/home/fulup/Workspace/AFB-binder/sec-gate-oidc/build/CMakeCacheForScript.cmake")
set(ColourBold "[1m")
set(ColourReset "[m")
set(Cyan "[36m")
set(DATADIR "var")
set(DEBUG_COMPILE_OPTIONS "-g-O0-ggdb")
set(DIRTY_FLAG " M conf.d/project/etc/oidc-local.json\n D conf.d/project/etc/oidc-nfc.json\n M conf.d/project/etc/oidc-oauth2.json\n D docs/5.1-onelogin-kickstart.md\n D docs/5.2-github-kickstart.md\n D docs/5.3-ldap-kickstart.md\n D docs/5.4-pam-kickstart.md\n D docs/5.5-phantauth-kickstart.md\n M docs/api-services-book.yml\n D libs/idps-builtin/CMakeLists.txt\n D libs/idps-builtin/idp-builtin.c\n D libs/idps-builtin/idp-github.c\n D libs/idps-builtin/idp-github.h\n D libs/idps-builtin/idp-ldap.c\n D libs/idps-builtin/idp-ldap.h\n D libs/idps-builtin/idp-oidc.c\n D libs/idps-builtin/idp-oidc.h\n D libs/pcscd-cient/00-README.md\n D src/_ToDo.fulup\n?? idps/\n?? libs/pcscd-cient/README.md\n?? plugins/oidc-pam/README.md")
set(ETCDIR "etc")
set(Esc "")
set(FIND_PACKAGE_MESSAGE_DETAILS_PkgConfig "[/usr/bin/pkg-config][v1.7.3()]")
set(GDB_INITIAL_BREAK "personality")
set(GIT_PROJECT_VERSION "personality")
set(Green "[32m")
set(HTTPDIR "htdocs")
set(INSTALL_PREFIX "/home/fulup/opt")
set(JSON_CHECKER "/home/fulup/opt")
set(KERNEL_VERSION "5.11.16")
set(LD_LIBRARY_PATH "/usr/local/lib64/usr/local/lib")
set(LIBDIR "lib")
set(LINUX_VERSION_CODE "330512")
set(LINUX_VERSION_CODE_LINE "#define LINUX_VERSION_CODE 330512")
set(LUA_CHECKER "luac-p")
set(MSVC_CXX_ARCHITECTURE_ID "luac-p")
set(MSVC_C_ARCHITECTURE_ID "luac-p")
set(Magenta "[35m")
set(NPKG_PROJECT_NAME "agl-afb-sgate-oidc")
set(OS "agl-afb-sgate-oidc")
set(OSDETECTED "fedora")
set(OSRELEASE "fedora")
set(OS_RELEASE_PATH "/etc/os-release")
set(PACKAGE_MESSAGE "Install widget file using in the target : afm-util install afb-sgate-oidc.wgt")
set(PATTERN "/home/fulup/Workspace/AFB-binder/sec-gate-oidc/conf.d/cmake/[0-9][0-9]-fedora*.cmake/home/fulup/Workspace/AFB-binder/sec-gate-oidc/conf.d/cmake.d/[0-9][0-9]-fedora*.cmakeconf.d/cmake/[0-9][0-9]-common*.cmakeconf.d/cmake.d/[0-9][0-9]-common*.cmake")
set(PKGCONFIG_FOUND "TRUE")
set(PKGOUT_DIR "package")
set(PKG_CONFIG "package")
set(PKG_CONFIG_EXECUTABLE "/usr/bin/pkg-config")
set(PKG_CONFIG_FOUND "TRUE")
set(PKG_CONFIG_NAMES "pkg-config")
set(PKG_CONFIG_USE_CMAKE_PREFIX_PATH "ON")
set(PKG_CONFIG_VERSION "1")
set(PKG_CONFIG_VERSION_STRING "1.7.3")
set(PKG_REQUIRED_LIST "libafblibcurlfedid-types")
set(PKG_TEMPLATE_PREFIX "/usr/share/cmake/Modules/CMakeAfbTemplates")
set(PRESET_CMAKE_SYSTEM_NAME "/usr/share/cmake/Modules/CMakeAfbTemplates")
set(PROFILING_COMPILE_OPTIONS "-g-O0-pg-Wp,-U_FORTIFY_SOURCE")
set(PROJECT_AGL_AUTOBUILD_DIR "/home/fulup/Workspace/AFB-binder/sec-gate-oidc/autobuild/agl")
set(PROJECT_APP_TEMPLATES_DIR "/usr/share/cmake/Modules/CMakeAfbTemplates/cmake/cmake.d/../..")
set(PROJECT_AUTHOR "Iot-Team")
set(PROJECT_AUTHOR_MAIL "secretariat@iot.bzh")
set(PROJECT_BINARY_DIR "/home/fulup/Workspace/AFB-binder/sec-gate-oidc/build")
set(PROJECT_CMAKE_CONF_DIR "conf.d")
set(PROJECT_DESCRIPTION "Provide authentication through OpenID")
set(PROJECT_HOMEPAGE_URL "https://github.com/redpesk-common/afb-oidc")
set(PROJECT_ICON "icon.jpg")
set(PROJECT_LICENSE "APL2.0")
set(PROJECT_LINUX_AUTOBUILD_DIR "/home/fulup/Workspace/AFB-binder/sec-gate-oidc/autobuild/linux")
set(PROJECT_NAME "afb-sgate-oidc")
set(PROJECT_PKG_BUILD_DIR "/home/fulup/Workspace/AFB-binder/sec-gate-oidc/build/package")
set(PROJECT_PKG_ENTRY_POINT "/home/fulup/Workspace/AFB-binder/sec-gate-oidc/conf.d/packaging")
set(PROJECT_PRETTY_NAME "OpenID Connect Extention for AFB-binder")
set(PROJECT_SOURCE_DIR "/home/fulup/Workspace/AFB-binder/sec-gate-oidc")
set(PROJECT_TEST_DIR "/home/fulup/Workspace/AFB-binder/sec-gate-oidc/test")
set(PROJECT_URL "https://github.com/redpesk-common/afb-oidc")
set(PROJECT_VERSION "1.0-eb68976-dirty")
set(PROJECT_VERSION_MAJOR "1")
set(PROJECT_VERSION_MINOR "1")
set(PROJECT_VERSION_PATCH "1")
set(PROJECT_VERSION_TWEAK "1")
set(PkgConfig_FOUND "TRUE")
set(RELEASE_COMPILE_OPTIONS "-O2-D_FORTIFY_SOURCE=2")
set(RUN_CONFIGURE "ON")
set(Red "[31m")
set(SANITIZERS_COMPILE_OPTIONS "-g-O0-fsanitize=address-fno-omit-frame-pointer")
set(TEMPLATE_DIR "/usr/share/cmake/Modules/CMakeAfbTemplates/cmake/cmake.d/../../template.d")
set(TMP_OSRELEASE "ID=fedora\n")
set(UNIX "1")
set(WIDGET_CONFIG_TEMPLATE "/home/fulup/Workspace/AFB-binder/sec-gate-oidc/conf.d/wgt/config.xml.in")
set(WIDGET_ENTRY_POINT "lib/afb-oidc.so")
set(WIDGET_ICON "/home/fulup/Workspace/AFB-binder/sec-gate-oidc/conf.d/wgt/icon.jpg")
set(WIDGET_TYPE "application/vnd.agl.service")
set(White "[37m")
set(XML_CHECKER "xmllint")
set(XPREFIX "fedid-types")
set(Yellow "[33m")
set(_CMAKE_CUDA_IMPLICIT_INCLUDE_DIRECTORIES_INIT "/usr/include")
set(_CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES_INIT "/usr/include")
set(_CMAKE_CXX_IPO_MAY_BE_SUPPORTED_BY_COMPILER "YES")
set(_CMAKE_CXX_IPO_SUPPORTED_BY_CMAKE "YES")
set(_CMAKE_CXX_PIE_MAY_BE_SUPPORTED_BY_LINKER "YES")
set(_CMAKE_C_IMPLICIT_INCLUDE_DIRECTORIES_INIT "/usr/include")
set(_CMAKE_C_IPO_MAY_BE_SUPPORTED_BY_COMPILER "YES")
set(_CMAKE_C_IPO_SUPPORTED_BY_CMAKE "YES")
set(_CMAKE_C_PIE_MAY_BE_SUPPORTED_BY_LINKER "YES")
set(_CMAKE_INSTALL_DIR "/usr")
set(_CMAKE_TOOLCHAIN_LOCATION "/usr/bin")
set(_ExternalProject_SELF "/usr/share/cmake/Modules/ExternalProject.cmake")
set(_ExternalProject_SELF_DIR "/usr/share/cmake/Modules")
set(_GNUInstallDirs_LAST_CMAKE_INSTALL_PREFIX "/usr/local")
set(_INCLUDED_FILE "/usr/share/cmake/Modules/Platform/Linux-GNU-CXX.cmake")
set(_INCLUDED_SYSTEM_INFO_FILE "/usr/share/cmake/Modules/Platform/Linux.cmake")
set(_IN_TC "/usr/share/cmake/Modules/Platform/Linux.cmake")
set(_LIBDIR_DEFAULT "lib64")
set(_PKG_CONFIG_FAILURE_MESSAGE "lib64")
set(_PKG_CONFIG_VERSION_ERROR "lib64")
set(_SET_CMAKE_CXX_COMPILER_ARCHITECTURE_ID "lib64")
set(_SET_CMAKE_CXX_COMPILER_SYSROOT "lib64")
set(_SET_CMAKE_C_COMPILER_ARCHITECTURE_ID "lib64")
set(_SET_CMAKE_C_COMPILER_SYSROOT "lib64")
set(__COMPILER_CMAKE_COMMON_COMPILER_MACROS "1")
set(__COMPILER_GNU "1")
set(__LINUX_COMPILER_GNU "1")
set(__UNIX_PATHS_INCLUDED "1")
set(__gcc_hints "/usr/bin")
set(__lto_flags "-flto-fno-fat-lto-objects")
set(__pch_header_C "c-header")
set(__pch_header_CXX "c++-header")
set(__pch_header_OBJC "objective-c-header")
set(__pch_header_OBJCXX "objective-c++-header")
set(__pkg_config_arguments_fedid-types "REQUIREDfedid-types")
set(__pkg_config_arguments_libafb "REQUIREDlibafb")
set(__pkg_config_arguments_libcurl "REQUIREDlibcurl")
set(__pkg_config_checked_fedid-types "1")
set(__pkg_config_checked_libafb "1")
set(__pkg_config_checked_libcurl "1")
set(__version_x "11")
set(__version_x_y "11.1")
set(_ep_documentation_line_count "1019")
set(_ep_func "ExternalProject_Add_StepDependencies")
set(_ep_hash_algos "MD5|SHA1|SHA224|SHA256|SHA384|SHA512|SHA3_224|SHA3_256|SHA3_384|SHA3_512")
set(_ep_hash_regex "^(MD5|SHA1|SHA224|SHA256|SHA384|SHA512|SHA3_224|SHA3_256|SHA3_384|SHA3_512)=([0-9A-Fa-f]+)$")
set(_ep_key "USES_TERMINAL")
set(_ep_keywords_ExternalProject_Add "^(PREFIX|TMP_DIR|STAMP_DIR|LOG_DIR|DOWNLOAD_DIR|SOURCE_DIR|BINARY_DIR|INSTALL_DIR|DOWNLOAD_COMMAND|URL|URL_HASH|URL_MD5|DOWNLOAD_NAME|DOWNLOAD_NO_EXTRACT|DOWNLOAD_NO_PROGRESS|TIMEOUT|INACTIVITY_TIMEOUT|HTTP_USERNAME|HTTP_PASSWORD|HTTP_HEADER|TLS_VERIFY|TLS_CAINFO|NETRC|NETRC_FILE|GIT_REPOSITORY|GIT_TAG|GIT_REMOTE_NAME|GIT_SUBMODULES|GIT_SUBMODULES_RECURSE|GIT_SHALLOW|GIT_PROGRESS|GIT_CONFIG|GIT_REMOTE_UPDATE_STRATEGY|SVN_REPOSITORY|SVN_REVISION|SVN_USERNAME|SVN_PASSWORD|SVN_TRUST_CERT|HG_REPOSITORY|HG_TAG|CVS_REPOSITORY|CVS_MODULE|CVS_TAG|UPDATE_COMMAND|UPDATE_DISCONNECTED|PATCH_COMMAND|CONFIGURE_COMMAND|CMAKE_COMMAND|CMAKE_GENERATOR|CMAKE_GENERATOR_PLATFORM|CMAKE_GENERATOR_TOOLSET|CMAKE_GENERATOR_INSTANCE|CMAKE_ARGS|CMAKE_CACHE_ARGS|CMAKE_CACHE_DEFAULT_ARGS|SOURCE_SUBDIR|BUILD_COMMAND|BUILD_IN_SOURCE|BUILD_ALWAYS|BUILD_BYPRODUCTS|INSTALL_COMMAND|TEST_COMMAND|TEST_BEFORE_INSTALL|TEST_AFTER_INSTALL|TEST_EXCLUDE_FROM_MAIN|LOG_DOWNLOAD|LOG_UPDATE|LOG_PATCH|LOG_CONFIGURE|LOG_BUILD|LOG_INSTALL|LOG_TEST|LOG_MERGED_STDOUTERR|LOG_OUTPUT_ON_FAILURE|USES_TERMINAL_DOWNLOAD|USES_TERMINAL_UPDATE|USES_TERMINAL_CONFIGURE|USES_TERMINAL_BUILD|USES_TERMINAL_INSTALL|USES_TERMINAL_TEST|DEPENDS|EXCLUDE_FROM_ALL|STEP_TARGETS|INDEPENDENT_STEP_TARGETS|LIST_SEPARATOR)$")
set(_ep_keywords_ExternalProject_Add_Step "^(COMMAND|COMMENT|DEPENDEES|DEPENDERS|DEPENDS|INDEPENDENT|BYPRODUCTS|ALWAYS|EXCLUDE_FROM_MAIN|WORKING_DIRECTORY|LOG|USES_TERMINAL)$")
set(_ep_keywords_ExternalProject_Add_StepDependencies "^()$")
set(_ep_keywords_ExternalProject_Add_StepTargets "^()$")
set(_ep_keywords_ExternalProject_Get_Property "^()$")
set(_imp_target "^()$")
set(_imp_target_global "^()$")
set(_lib_dir "^()$")
set(_no_cmake_environment_path "^()$")
set(_no_cmake_path "^()$")
set(_pkg "^()$")
set(_pkg_check_modules_cnt "1")
set(_pkg_check_modules_exist_query "--print-errors--short-errors--existsfedid-types")
set(_pkg_check_modules_list "fedid-types")
set(_pkg_check_modules_packages "fedid-types")
set(_pkg_check_modules_pkg "fedid-types")
set(_pkg_check_modules_pkg_name "fedid-types")
set(_pkg_check_prefix "fedid-types")
set(_pkg_is_required "1")
set(_pkg_is_silent "1")
set(_pkg_modules "fedid-types")
set(_pkgconfig_LDFLAGS "-L/usr/local/fedid-binding/lib-lfedid-types")
set(_pkgconfig_LIBRARIES "fedid-types")
set(_pkgconfig_LIBRARY_DIRS "/usr/local/fedid-binding/lib")
set(_pkgconfig_STATIC_LDFLAGS "-L/usr/local/fedid-binding/lib-lfedid-types")
set(_pkgconfig_STATIC_LIBRARIES "fedid-types")
set(_pkgconfig_STATIC_LIBRARY_DIRS "/usr/local/fedid-binding/lib")
set(_pkgconfig_VERSION "1.0")
set(_pkgconfig_error "1.0")
set(_pkgconfig_failed "1.0")
set(_pkgconfig_invoke_result "1.0")
set(_pkgconfig_retval "1.0")
set(_prefix_dir "1.0")
set(a "5")
set(afb-sgate-oidc_BINARY_DIR "/home/fulup/Workspace/AFB-binder/sec-gate-oidc/build")
set(afb-sgate-oidc_DESCRIPTION "Provide authentication through OpenID")
set(afb-sgate-oidc_HOMEPAGE_URL "https://github.com/redpesk-common/afb-oidc")
set(afb-sgate-oidc_SOURCE_DIR "/home/fulup/Workspace/AFB-binder/sec-gate-oidc")
set(afb-sgate-oidc_VERSION "1.0")
set(afb-sgate-oidc_VERSION_MAJOR "1")
set(afb-sgate-oidc_VERSION_MINOR "1")
set(afb-sgate-oidc_VERSION_PATCH "1")
set(afb-sgate-oidc_VERSION_TWEAK "1")
set(b "11")
set(c "16")
set(dir "16")
set(distro_cmakefiles "/home/fulup/Workspace/AFB-binder/sec-gate-oidc/conf.d/cmake/00-fedora-config.cmake")
set(extension "/home/fulup/Workspace/AFB-binder/sec-gate-oidc/conf.d/cmake/00-fedora-config.cmake")
set(fedid-types_CFLAGS "/home/fulup/Workspace/AFB-binder/sec-gate-oidc/conf.d/cmake/00-fedora-config.cmake")
set(fedid-types_CFLAGS_I "/home/fulup/Workspace/AFB-binder/sec-gate-oidc/conf.d/cmake/00-fedora-config.cmake")
set(fedid-types_CFLAGS_OTHER "/home/fulup/Workspace/AFB-binder/sec-gate-oidc/conf.d/cmake/00-fedora-config.cmake")
set(fedid-types_FOUND "1")
set(fedid-types_INCLUDEDIR "/usr/local/include")
set(fedid-types_INCLUDE_DIRS "/usr/local/include")
set(fedid-types_LDFLAGS "-L/usr/local/fedid-binding/lib-lfedid-types")
set(fedid-types_LDFLAGS_OTHER "-L/usr/local/fedid-binding/lib-lfedid-types")
set(fedid-types_LIBDIR "/usr/local/lib64")
set(fedid-types_LIBRARIES "fedid-types")
set(fedid-types_LIBRARY_DIRS "/usr/local/fedid-binding/lib")
set(fedid-types_LIBS "/usr/local/fedid-binding/lib")
set(fedid-types_LIBS_L "/usr/local/fedid-binding/lib")
set(fedid-types_LIBS_OTHER "/usr/local/fedid-binding/lib")
set(fedid-types_LIBS_PATHS "/usr/local/fedid-binding/lib")
set(fedid-types_LINK_LIBRARIES "/usr/local/fedid-binding/lib/libfedid-types.so")
set(fedid-types_MODULE_NAME "fedid-types")
set(fedid-types_PREFIX "/usr/local")
set(fedid-types_STATIC_CFLAGS "/usr/local")
set(fedid-types_STATIC_CFLAGS_I "/usr/local")
set(fedid-types_STATIC_CFLAGS_OTHER "/usr/local")
set(fedid-types_STATIC_INCLUDE_DIRS "/usr/local")
set(fedid-types_STATIC_LDFLAGS "-L/usr/local/fedid-binding/lib-lfedid-types")
set(fedid-types_STATIC_LDFLAGS_OTHER "-L/usr/local/fedid-binding/lib-lfedid-types")
set(fedid-types_STATIC_LIBDIR "-L/usr/local/fedid-binding/lib-lfedid-types")
set(fedid-types_STATIC_LIBRARIES "fedid-types")
set(fedid-types_STATIC_LIBRARY_DIRS "/usr/local/fedid-binding/lib")
set(fedid-types_STATIC_LIBS "/usr/local/fedid-binding/lib")
set(fedid-types_STATIC_LIBS_L "/usr/local/fedid-binding/lib")
set(fedid-types_STATIC_LIBS_OTHER "/usr/local/fedid-binding/lib")
set(fedid-types_STATIC_LIBS_PATHS "/usr/local/fedid-binding/lib")
set(fedid-types_VERSION "1.0")
set(fedid-types_fedid-types_INCLUDEDIR "1.0")
set(fedid-types_fedid-types_LIBDIR "1.0")
set(fedid-types_fedid-types_PREFIX "1.0")
set(fedid-types_fedid-types_VERSION "1.0")
set(file "/usr/share/cmake/Modules/CMakeAfbTemplates/cmake/cmake.d/04-extra_targets.cmake")
set(gcc_minimal_version "4.9")
set(home_cmakefiles "4.9")
set(l "4.9")
set(lang "4.9")
set(libafb_CFLAGS "-I/usr/include/json-c-I/usr/include/uuid-I/usr/include/p11-kit-1")
set(libafb_CFLAGS_I "-I/usr/include/json-c-I/usr/include/uuid-I/usr/include/p11-kit-1")
set(libafb_CFLAGS_OTHER "-I/usr/include/json-c-I/usr/include/uuid-I/usr/include/p11-kit-1")
set(libafb_FOUND "1")
set(libafb_INCLUDEDIR "1")
set(libafb_INCLUDE_DIRS "/usr/include/json-c/usr/include/uuid/usr/include/p11-kit-1")
set(libafb_LDFLAGS "-lafb-ljson-c-lsystemd-lcynagora-luuid-lmicrohttpd")
set(libafb_LDFLAGS_OTHER "-lafb-ljson-c-lsystemd-lcynagora-luuid-lmicrohttpd")
set(libafb_LIBDIR "-lafb-ljson-c-lsystemd-lcynagora-luuid-lmicrohttpd")
set(libafb_LIBRARIES "afbjson-csystemdcynagorauuidmicrohttpd")
set(libafb_LIBRARY_DIRS "afbjson-csystemdcynagorauuidmicrohttpd")
set(libafb_LIBS "afbjson-csystemdcynagorauuidmicrohttpd")
set(libafb_LIBS_L "afbjson-csystemdcynagorauuidmicrohttpd")
set(libafb_LIBS_OTHER "afbjson-csystemdcynagorauuidmicrohttpd")
set(libafb_LIBS_PATHS "afbjson-csystemdcynagorauuidmicrohttpd")
set(libafb_LINK_LIBRARIES "/usr/local/lib64/libafb.so/usr/lib64/libjson-c.so/usr/lib64/libsystemd.so/usr/local/lib64/libcynagora.so/usr/lib64/libuuid.so/usr/lib64/libmicrohttpd.so")
set(libafb_MODULE_NAME "libafb")
set(libafb_PREFIX "libafb")
set(libafb_STATIC_CFLAGS "-I/usr/include/json-c-I/usr/include/uuid-I/usr/include/p11-kit-1")
set(libafb_STATIC_CFLAGS_I "-I/usr/include/json-c-I/usr/include/uuid-I/usr/include/p11-kit-1")
set(libafb_STATIC_CFLAGS_OTHER "-I/usr/include/json-c-I/usr/include/uuid-I/usr/include/p11-kit-1")
set(libafb_STATIC_INCLUDE_DIRS "/usr/include/json-c/usr/include/uuid/usr/include/p11-kit-1")
set(libafb_STATIC_LDFLAGS "-lafb-lmagic-ldl-lrt-ljson-c-lsystemd-lcynagora-luuid-lmicrohttpd-lpthread-lgnutls-pthread-ltspi-lgmp-lunistring-lnettle-lhogweed-lgmp-lnettle-ltasn1-lidn2-lunistring-lp11-kit")
set(libafb_STATIC_LDFLAGS_OTHER "-pthread")
set(libafb_STATIC_LIBDIR "-pthread")
set(libafb_STATIC_LIBRARIES "afbmagicdlrtjson-csystemdcynagorauuidmicrohttpdpthreadgnutlstspigmpunistringnettlehogweedgmpnettletasn1idn2unistringp11-kit")
set(libafb_STATIC_LIBRARY_DIRS "afbmagicdlrtjson-csystemdcynagorauuidmicrohttpdpthreadgnutlstspigmpunistringnettlehogweedgmpnettletasn1idn2unistringp11-kit")
set(libafb_STATIC_LIBS "afbmagicdlrtjson-csystemdcynagorauuidmicrohttpdpthreadgnutlstspigmpunistringnettlehogweedgmpnettletasn1idn2unistringp11-kit")
set(libafb_STATIC_LIBS_L "afbmagicdlrtjson-csystemdcynagorauuidmicrohttpdpthreadgnutlstspigmpunistringnettlehogweedgmpnettletasn1idn2unistringp11-kit")
set(libafb_STATIC_LIBS_OTHER "afbmagicdlrtjson-csystemdcynagorauuidmicrohttpdpthreadgnutlstspigmpunistringnettlehogweedgmpnettletasn1idn2unistringp11-kit")
set(libafb_STATIC_LIBS_PATHS "afbmagicdlrtjson-csystemdcynagorauuidmicrohttpdpthreadgnutlstspigmpunistringnettlehogweedgmpnettletasn1idn2unistringp11-kit")
set(libafb_VERSION "4.0")
set(libafb_libafb_INCLUDEDIR "4.0")
set(libafb_libafb_LIBDIR "4.0")
set(libafb_libafb_PREFIX "4.0")
set(libafb_libafb_VERSION "4.0")
set(libcurl_CFLAGS "4.0")
set(libcurl_CFLAGS_I "4.0")
set(libcurl_CFLAGS_OTHER "4.0")
set(libcurl_FOUND "1")
set(libcurl_INCLUDEDIR "/usr/include")
set(libcurl_INCLUDE_DIRS "/usr/include")
set(libcurl_LDFLAGS "-lcurl")
set(libcurl_LDFLAGS_OTHER "-lcurl")
set(libcurl_LIBDIR "/usr/lib64")
set(libcurl_LIBRARIES "curl")
set(libcurl_LIBRARY_DIRS "curl")
set(libcurl_LIBS "curl")
set(libcurl_LIBS_L "curl")
set(libcurl_LIBS_OTHER "curl")
set(libcurl_LIBS_PATHS "curl")
set(libcurl_LINK_LIBRARIES "/usr/lib64/libcurl.so")
set(libcurl_MODULE_NAME "libcurl")
set(libcurl_PREFIX "/usr")
set(libcurl_STATIC_CFLAGS "/usr")
set(libcurl_STATIC_CFLAGS_I "/usr")
set(libcurl_STATIC_CFLAGS_OTHER "/usr")
set(libcurl_STATIC_INCLUDE_DIRS "/usr")
set(libcurl_STATIC_LDFLAGS "-lcurl-lnghttp2-lidn2-lssh-lssh-lpsl-lssl-lcrypto-lssl-lcrypto-Wl,-z,relro-Wl,--as-needed-Wl,-z,now-lgssapi_krb5-lkrb5-lk5crypto-lcom_err-lldap-llber-lbrotlidec-lbrotlidec-lz-pthread")
set(libcurl_STATIC_LDFLAGS_OTHER "-Wl,-z,relro-Wl,--as-needed-Wl,-z,now-pthread")
set(libcurl_STATIC_LIBDIR "-Wl,-z,relro-Wl,--as-needed-Wl,-z,now-pthread")
set(libcurl_STATIC_LIBRARIES "curlnghttp2idn2sshsshpslsslcryptosslcryptogssapi_krb5krb5k5cryptocom_errldaplberbrotlidecbrotlidecz")
set(libcurl_STATIC_LIBRARY_DIRS "curlnghttp2idn2sshsshpslsslcryptosslcryptogssapi_krb5krb5k5cryptocom_errldaplberbrotlidecbrotlidecz")
set(libcurl_STATIC_LIBS "curlnghttp2idn2sshsshpslsslcryptosslcryptogssapi_krb5krb5k5cryptocom_errldaplberbrotlidecbrotlidecz")
set(libcurl_STATIC_LIBS_L "curlnghttp2idn2sshsshpslsslcryptosslcryptogssapi_krb5krb5k5cryptocom_errldaplberbrotlidecbrotlidecz")
set(libcurl_STATIC_LIBS_OTHER "curlnghttp2idn2sshsshpslsslcryptosslcryptogssapi_krb5krb5k5cryptocom_errldaplberbrotlidecbrotlidecz")
set(libcurl_STATIC_LIBS_PATHS "curlnghttp2idn2sshsshpslsslcryptosslcryptogssapi_krb5krb5k5cryptocom_errldaplberbrotlidecbrotlidecz")
set(libcurl_VERSION "7.76.1")
set(libcurl_libcurl_INCLUDEDIR "7.76.1")
set(libcurl_libcurl_LIBDIR "7.76.1")
set(libcurl_libcurl_PREFIX "7.76.1")
set(libcurl_libcurl_VERSION "7.76.1")
set(line "7.76.1")
set(lines ".. command:: ExternalProject_Add    ``PREFIX <dir>``    ``TMP_DIR <dir>``    ``STAMP_DIR <dir>``    ``LOG_DIR <dir>``    ``DOWNLOAD_DIR <dir>``    ``SOURCE_DIR <dir>``    ``BINARY_DIR <dir>``    ``INSTALL_DIR <dir>``    ``DOWNLOAD_COMMAND <cmd>...``      ``URL <url1> [<url2>...]``      ``URL_HASH <algo>=<hashValue>``      ``URL_MD5 <md5>``      ``DOWNLOAD_NAME <fname>``      ``DOWNLOAD_NO_EXTRACT <bool>``      ``DOWNLOAD_NO_PROGRESS <bool>``      ``TIMEOUT <seconds>``      ``INACTIVITY_TIMEOUT <seconds>``      ``HTTP_USERNAME <username>``      ``HTTP_PASSWORD <password>``      ``HTTP_HEADER <header1> [<header2>...]``      ``TLS_VERIFY <bool>``      ``TLS_CAINFO <file>``      ``NETRC <level>``      ``NETRC_FILE <file>``      ``GIT_REPOSITORY <url>``      ``GIT_TAG <tag>``      ``GIT_REMOTE_NAME <name>``      ``GIT_SUBMODULES <module>...``      ``GIT_SUBMODULES_RECURSE <bool>``      ``GIT_SHALLOW <bool>``      ``GIT_PROGRESS <bool>``      ``GIT_CONFIG <option1> [<option2>...]``      ``GIT_REMOTE_UPDATE_STRATEGY <strategy>``      ``SVN_REPOSITORY <url>``      ``SVN_REVISION -r<rev>``      ``SVN_USERNAME <username>``      ``SVN_PASSWORD <password>``      ``SVN_TRUST_CERT <bool>``      ``HG_REPOSITORY <url>``      ``HG_TAG <tag>``      ``CVS_REPOSITORY <cvsroot>``      ``CVS_MODULE <mod>``      ``CVS_TAG <tag>``    ``UPDATE_COMMAND <cmd>...``    ``UPDATE_DISCONNECTED <bool>``    ``PATCH_COMMAND <cmd>...``    ``CONFIGURE_COMMAND <cmd>...``    ``CMAKE_COMMAND /.../cmake``    ``CMAKE_GENERATOR <gen>``    ``CMAKE_GENERATOR_PLATFORM <platform>``    ``CMAKE_GENERATOR_TOOLSET <toolset>``    ``CMAKE_GENERATOR_INSTANCE <instance>``    ``CMAKE_ARGS <arg>...``    ``CMAKE_CACHE_ARGS <arg>...``    ``CMAKE_CACHE_DEFAULT_ARGS <arg>...``    ``SOURCE_SUBDIR <dir>``    ``BUILD_COMMAND <cmd>...``    ``BUILD_IN_SOURCE <bool>``    ``BUILD_ALWAYS <bool>``    ``BUILD_BYPRODUCTS <file>...``    ``INSTALL_COMMAND <cmd>...``    ``TEST_COMMAND <cmd>...``    ``TEST_BEFORE_INSTALL <bool>``    ``TEST_AFTER_INSTALL <bool>``    ``TEST_EXCLUDE_FROM_MAIN <bool>``    ``LOG_DOWNLOAD <bool>``    ``LOG_UPDATE <bool>``    ``LOG_PATCH <bool>``    ``LOG_CONFIGURE <bool>``    ``LOG_BUILD <bool>``    ``LOG_INSTALL <bool>``    ``LOG_TEST <bool>``    ``LOG_MERGED_STDOUTERR <bool>``    ``LOG_OUTPUT_ON_FAILURE <bool>``    ``USES_TERMINAL_DOWNLOAD <bool>``    ``USES_TERMINAL_UPDATE <bool>``    ``USES_TERMINAL_CONFIGURE <bool>``    ``USES_TERMINAL_BUILD <bool>``    ``USES_TERMINAL_INSTALL <bool>``    ``USES_TERMINAL_TEST <bool>``    ``DEPENDS <targets>...``    ``EXCLUDE_FROM_ALL <bool>``    ``STEP_TARGETS <step-target>...``    ``INDEPENDENT_STEP_TARGETS <step-target>...``    ``LIST_SEPARATOR <sep>``    ``COMMAND <cmd>...``.. command:: ExternalProject_Get_Property.. command:: ExternalProject_Add_Step  ``COMMAND <cmd>...``  ``COMMENT \"<text>...\"``  ``DEPENDEES <step>...``  ``DEPENDERS <step>...``  ``DEPENDS <file>...``  ``INDEPENDENT <bool>``  ``BYPRODUCTS <file>...``  ``ALWAYS <bool>``  ``EXCLUDE_FROM_MAIN <bool>``  ``WORKING_DIRECTORY <dir>``  ``LOG <bool>``  ``USES_TERMINAL <bool>``.. command:: ExternalProject_Add_StepTargets.. command:: ExternalProject_Add_StepDependencies")
set(link_libraries "-lafb-ljson-c-lsystemd-lcynagora-luuid-lmicrohttpd-lcurl-L/usr/local/fedid-binding/lib-lfedid-types")
set(option "-lafb-ljson-c-lsystemd-lcynagora-luuid-lmicrohttpd-lcurl-L/usr/local/fedid-binding/lib-lfedid-types")
set(pkg_count "1")
set(pkgcfg_lib_fedid-types_fedid-types "/usr/local/fedid-binding/lib/libfedid-types.so")
set(pkgcfg_lib_libafb_afb "/usr/local/lib64/libafb.so")
set(pkgcfg_lib_libafb_cynagora "/usr/local/lib64/libcynagora.so")
set(pkgcfg_lib_libafb_json-c "/usr/lib64/libjson-c.so")
set(pkgcfg_lib_libafb_microhttpd "/usr/lib64/libmicrohttpd.so")
set(pkgcfg_lib_libafb_systemd "/usr/lib64/libsystemd.so")
set(pkgcfg_lib_libafb_uuid "/usr/lib64/libuuid.so")
set(pkgcfg_lib_libcurl_curl "/usr/lib64/libcurl.so")
set(prefix_result "/usr/local/lib64")
set(project_cmakefiles "/usr/share/cmake/Modules/CMakeAfbTemplates/cmake/cmake.d/01-build_options.cmake/usr/share/cmake/Modules/CMakeAfbTemplates/cmake/cmake.d/02-variables.cmake/usr/share/cmake/Modules/CMakeAfbTemplates/cmake/cmake.d/03-macros.cmake/usr/share/cmake/Modules/CMakeAfbTemplates/cmake/cmake.d/04-extra_targets.cmake")
set(system_cmakefiles "/usr/share/cmake/Modules/CMakeAfbTemplates/cmake/cmake.d/01-build_options.cmake/usr/share/cmake/Modules/CMakeAfbTemplates/cmake/cmake.d/02-variables.cmake/usr/share/cmake/Modules/CMakeAfbTemplates/cmake/cmake.d/03-macros.cmake/usr/share/cmake/Modules/CMakeAfbTemplates/cmake/cmake.d/04-extra_targets.cmake")
set(type "/usr/share/cmake/Modules/CMakeAfbTemplates/cmake/cmake.d/01-build_options.cmake/usr/share/cmake/Modules/CMakeAfbTemplates/cmake/cmake.d/02-variables.cmake/usr/share/cmake/Modules/CMakeAfbTemplates/cmake/cmake.d/03-macros.cmake/usr/share/cmake/Modules/CMakeAfbTemplates/cmake/cmake.d/04-extra_targets.cmake")
set(uselib32 "TRUE")
set(uselib64 "TRUE")
set(uselibx32 "TRUE")
set(val "TRUE")
set(var "TRUE")
set(variable "TRUE")
